// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public final class Api extends com.google.protobuf.GeneratedFile {
  private Api() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "Api");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_Object_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_Entry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_Entry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_Paginator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_Paginator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_PageInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_PageInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_GetResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_GetResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_ListenMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_ListenMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_EventCall_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_EventCall_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_octopus_sdk_v1_ListenRegister_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_octopus_sdk_v1_ListenRegister_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014v1/api.proto\022\016octopus_sdk.v1\032\034google/p" +
      "rotobuf/struct.proto\032\033google/protobuf/em" +
      "pty.proto\032\037google/protobuf/timestamp.pro" +
      "to\032\034google/api/annotations.proto\"\345\001\n\006Obj" +
      "ect\022\020\n\003key\030\001 \001(\tR\003key\022+\n\004data\030\002 \001(\0132\027.go" +
      "ogle.protobuf.StructR\004data\022>\n\nexpired_at" +
      "\030\003 \001(\0132\032.google.protobuf.TimestampH\000R\tex" +
      "piredAt\210\001\001\022>\n\ndeleted_at\030\004 \001(\0132\032.google." +
      "protobuf.TimestampH\001R\tdeletedAt\210\001\001B\r\n\013_e" +
      "xpired_atB\r\n\013_deleted_at\"\236\001\n\005Entry\022.\n\006ob" +
      "ject\030\001 \001(\0132\026.octopus_sdk.v1.ObjectR\006obje" +
      "ct\0229\n\ncreated_at\030\002 \001(\0132\032.google.protobuf" +
      ".TimestampR\tcreatedAt\022\032\n\010revision\030\003 \001(\003R" +
      "\010revision\022\016\n\002id\030\004 \001(\tR\002id\"\315\003\n\nGetRequest" +
      "\022\037\n\013key_pattern\030\001 \001(\tR\nkeyPattern\022,\n\017inc" +
      "lude_expired\030\002 \001(\010H\000R\016includeExpired\210\001\001\022" +
      "T\n\026created_at_range_start\030\003 \001(\0132\032.google" +
      ".protobuf.TimestampH\001R\023createdAtRangeSta" +
      "rt\210\001\001\022P\n\024created_at_range_end\030\004 \001(\0132\032.go" +
      "ogle.protobuf.TimestampH\002R\021createdAtRang" +
      "eEnd\210\001\001\022$\n\013data_filter\030\005 \001(\tH\003R\ndataFilt" +
      "er\210\001\001\022<\n\tpaginator\030\006 \001(\0132\031.octopus_sdk.v" +
      "1.PaginatorH\004R\tpaginator\210\001\001B\022\n\020_include_" +
      "expiredB\031\n\027_created_at_range_startB\027\n\025_c" +
      "reated_at_range_endB\016\n\014_data_filterB\014\n\n_" +
      "paginator\"<\n\tPaginator\022\022\n\004page\030\001 \001(\005R\004pa" +
      "ge\022\033\n\tpage_size\030\002 \001(\005R\010pageSize\"\373\001\n\010Page" +
      "Info\022!\n\014current_page\030\001 \001(\005R\013currentPage\022" +
      "*\n\021current_page_size\030\002 \001(\005R\017currentPageS" +
      "ize\022\037\n\013total_pages\030\003 \001(\005R\ntotalPages\022\037\n\013" +
      "total_items\030\004 \001(\003R\ntotalItems\022 \n\tnext_pa" +
      "ge\030\005 \001(\005H\000R\010nextPage\210\001\001\022 \n\tprev_page\030\006 \001" +
      "(\005H\001R\010prevPage\210\001\001B\014\n\n_next_pageB\014\n\n_prev" +
      "_page\"u\n\013GetResponse\022/\n\007entries\030\001 \003(\0132\025." +
      "octopus_sdk.v1.EntryR\007entries\0225\n\tpage_in" +
      "fo\030\002 \001(\0132\030.octopus_sdk.v1.PageInfoR\010page" +
      "Info\"\215\001\n\rListenMessage\0227\n\010callback\030\001 \001(\013" +
      "2\031.octopus_sdk.v1.EventCallH\000R\010callback\022" +
      "<\n\010register\030\002 \001(\0132\036.octopus_sdk.v1.Liste" +
      "nRegisterH\000R\010registerB\005\n\003msg\"T\n\tEventCal" +
      "l\022.\n\006object\030\001 \001(\0132\026.octopus_sdk.v1.Objec" +
      "tR\006object\022\027\n\007call_id\030\002 \001(\tR\006callId\"M\n\016Li" +
      "stenRegister\022\037\n\013key_pattern\030\001 \001(\tR\nkeyPa" +
      "ttern\022\032\n\010priority\030\002 \001(\005R\010priority2\306\002\n\007Oc" +
      "topus\022S\n\003Get\022\032.octopus_sdk.v1.GetRequest" +
      "\032\033.octopus_sdk.v1.GetResponse\"\023\202\323\344\223\002\r\022\013/" +
      "v1/entries\022O\n\005Write\022\026.octopus_sdk.v1.Obj" +
      "ect\032\026.google.protobuf.Empty\"\026\202\323\344\223\002\020\"\013/v1" +
      "/objects:\001*\022M\n\004Call\022\026.octopus_sdk.v1.Obj" +
      "ect\032\025.octopus_sdk.v1.Entry\"\026\202\323\344\223\002\020\"\013/v1/" +
      "entries:\001*\022F\n\006Listen\022\035.octopus_sdk.v1.Li" +
      "stenMessage\032\031.octopus_sdk.v1.EventCall(\001" +
      "0\001BN\n\030studio.o7.octopus.sdk.v1P\001Z0github" +
      ".com/o7studios/octopus-sdk/go/v1;octopus" +
      "v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_octopus_sdk_v1_Object_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_octopus_sdk_v1_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_Object_descriptor,
        new java.lang.String[] { "Key", "Data", "ExpiredAt", "DeletedAt", });
    internal_static_octopus_sdk_v1_Entry_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_octopus_sdk_v1_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_Entry_descriptor,
        new java.lang.String[] { "Object", "CreatedAt", "Revision", "Id", });
    internal_static_octopus_sdk_v1_GetRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_octopus_sdk_v1_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_GetRequest_descriptor,
        new java.lang.String[] { "KeyPattern", "IncludeExpired", "CreatedAtRangeStart", "CreatedAtRangeEnd", "DataFilter", "Paginator", });
    internal_static_octopus_sdk_v1_Paginator_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_octopus_sdk_v1_Paginator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_Paginator_descriptor,
        new java.lang.String[] { "Page", "PageSize", });
    internal_static_octopus_sdk_v1_PageInfo_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_octopus_sdk_v1_PageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_PageInfo_descriptor,
        new java.lang.String[] { "CurrentPage", "CurrentPageSize", "TotalPages", "TotalItems", "NextPage", "PrevPage", });
    internal_static_octopus_sdk_v1_GetResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_octopus_sdk_v1_GetResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_GetResponse_descriptor,
        new java.lang.String[] { "Entries", "PageInfo", });
    internal_static_octopus_sdk_v1_ListenMessage_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_octopus_sdk_v1_ListenMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_ListenMessage_descriptor,
        new java.lang.String[] { "Callback", "Register", "Msg", });
    internal_static_octopus_sdk_v1_EventCall_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_octopus_sdk_v1_EventCall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_EventCall_descriptor,
        new java.lang.String[] { "Object", "CallId", });
    internal_static_octopus_sdk_v1_ListenRegister_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_octopus_sdk_v1_ListenRegister_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_octopus_sdk_v1_ListenRegister_descriptor,
        new java.lang.String[] { "KeyPattern", "Priority", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
