// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The underlying object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   * @return Whether the object field is set.
   */
  boolean hasObject();
  /**
   * <pre>
   * The underlying object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   * @return The object.
   */
  studio.o7.octopus.sdk.v1.Object getObject();
  /**
   * <pre>
   * The underlying object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   */
  studio.o7.octopus.sdk.v1.ObjectOrBuilder getObjectOrBuilder();

  /**
   * <pre>
   * Entry creation timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "createdAt"];</code>
   * @return Whether the createdAt field is set.
   */
  boolean hasCreatedAt();
  /**
   * <pre>
   * Entry creation timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  com.google.protobuf.Timestamp getCreatedAt();
  /**
   * <pre>
   * Entry creation timestamp.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp created_at = 2 [json_name = "createdAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder();

  /**
   * <pre>
   * Revision number, incremented on every update.
   * </pre>
   *
   * <code>int64 revision = 3 [json_name = "revision"];</code>
   * @return The revision.
   */
  long getRevision();

  /**
   * <pre>
   * Unique identifier for this entry.
   * </pre>
   *
   * <code>string id = 4 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Unique identifier for this entry.
   * </pre>
   *
   * <code>string id = 4 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
