// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface EventCallOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.EventCall)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The affected object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   * @return Whether the object field is set.
   */
  boolean hasObject();
  /**
   * <pre>
   * The affected object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   * @return The object.
   */
  studio.o7.octopus.sdk.v1.Object getObject();
  /**
   * <pre>
   * The affected object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   */
  studio.o7.octopus.sdk.v1.ObjectOrBuilder getObjectOrBuilder();

  /**
   * <pre>
   * Unique ID for this event call (useful for tracking).
   * </pre>
   *
   * <code>string call_id = 2 [json_name = "callId"];</code>
   * @return The callId.
   */
  java.lang.String getCallId();
  /**
   * <pre>
   * Unique ID for this event call (useful for tracking).
   * </pre>
   *
   * <code>string call_id = 2 [json_name = "callId"];</code>
   * @return The bytes for callId.
   */
  com.google.protobuf.ByteString
      getCallIdBytes();
}
