// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

/**
 * <pre>
 * *
 * Represents a event in the stream.
 * </pre>
 *
 * Protobuf type {@code octopus_sdk.v1.EventCall}
 */
@com.google.protobuf.Generated
public final class EventCall extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:octopus_sdk.v1.EventCall)
    EventCallOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "EventCall");
  }
  // Use EventCall.newBuilder() to construct.
  private EventCall(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EventCall() {
    callId_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_EventCall_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_EventCall_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studio.o7.octopus.sdk.v1.EventCall.class, studio.o7.octopus.sdk.v1.EventCall.Builder.class);
  }

  private int bitField0_;
  public static final int OBJECT_FIELD_NUMBER = 1;
  private studio.o7.octopus.sdk.v1.Object object_;
  /**
   * <pre>
   * The affected object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   * @return Whether the object field is set.
   */
  @java.lang.Override
  public boolean hasObject() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The affected object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   * @return The object.
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.Object getObject() {
    return object_ == null ? studio.o7.octopus.sdk.v1.Object.getDefaultInstance() : object_;
  }
  /**
   * <pre>
   * The affected object.
   * </pre>
   *
   * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.ObjectOrBuilder getObjectOrBuilder() {
    return object_ == null ? studio.o7.octopus.sdk.v1.Object.getDefaultInstance() : object_;
  }

  public static final int CALL_ID_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object callId_ = "";
  /**
   * <pre>
   * Unique ID for this event call (useful for tracking).
   * </pre>
   *
   * <code>string call_id = 2 [json_name = "callId"];</code>
   * @return The callId.
   */
  @java.lang.Override
  public java.lang.String getCallId() {
    java.lang.Object ref = callId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      callId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique ID for this event call (useful for tracking).
   * </pre>
   *
   * <code>string call_id = 2 [json_name = "callId"];</code>
   * @return The bytes for callId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCallIdBytes() {
    java.lang.Object ref = callId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      callId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getObject());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(callId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, callId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getObject());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(callId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, callId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studio.o7.octopus.sdk.v1.EventCall)) {
      return super.equals(obj);
    }
    studio.o7.octopus.sdk.v1.EventCall other = (studio.o7.octopus.sdk.v1.EventCall) obj;

    if (hasObject() != other.hasObject()) return false;
    if (hasObject()) {
      if (!getObject()
          .equals(other.getObject())) return false;
    }
    if (!getCallId()
        .equals(other.getCallId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasObject()) {
      hash = (37 * hash) + OBJECT_FIELD_NUMBER;
      hash = (53 * hash) + getObject().hashCode();
    }
    hash = (37 * hash) + CALL_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCallId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static studio.o7.octopus.sdk.v1.EventCall parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static studio.o7.octopus.sdk.v1.EventCall parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.EventCall parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studio.o7.octopus.sdk.v1.EventCall prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * Represents a event in the stream.
   * </pre>
   *
   * Protobuf type {@code octopus_sdk.v1.EventCall}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:octopus_sdk.v1.EventCall)
      studio.o7.octopus.sdk.v1.EventCallOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_EventCall_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_EventCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studio.o7.octopus.sdk.v1.EventCall.class, studio.o7.octopus.sdk.v1.EventCall.Builder.class);
    }

    // Construct using studio.o7.octopus.sdk.v1.EventCall.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetObjectFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      object_ = null;
      if (objectBuilder_ != null) {
        objectBuilder_.dispose();
        objectBuilder_ = null;
      }
      callId_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_EventCall_descriptor;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.EventCall getDefaultInstanceForType() {
      return studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance();
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.EventCall build() {
      studio.o7.octopus.sdk.v1.EventCall result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.EventCall buildPartial() {
      studio.o7.octopus.sdk.v1.EventCall result = new studio.o7.octopus.sdk.v1.EventCall(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(studio.o7.octopus.sdk.v1.EventCall result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.object_ = objectBuilder_ == null
            ? object_
            : objectBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.callId_ = callId_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studio.o7.octopus.sdk.v1.EventCall) {
        return mergeFrom((studio.o7.octopus.sdk.v1.EventCall)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studio.o7.octopus.sdk.v1.EventCall other) {
      if (other == studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance()) return this;
      if (other.hasObject()) {
        mergeObject(other.getObject());
      }
      if (!other.getCallId().isEmpty()) {
        callId_ = other.callId_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetObjectFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              callId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private studio.o7.octopus.sdk.v1.Object object_;
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.Object, studio.o7.octopus.sdk.v1.Object.Builder, studio.o7.octopus.sdk.v1.ObjectOrBuilder> objectBuilder_;
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     * @return Whether the object field is set.
     */
    public boolean hasObject() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     * @return The object.
     */
    public studio.o7.octopus.sdk.v1.Object getObject() {
      if (objectBuilder_ == null) {
        return object_ == null ? studio.o7.octopus.sdk.v1.Object.getDefaultInstance() : object_;
      } else {
        return objectBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     */
    public Builder setObject(studio.o7.octopus.sdk.v1.Object value) {
      if (objectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        object_ = value;
      } else {
        objectBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     */
    public Builder setObject(
        studio.o7.octopus.sdk.v1.Object.Builder builderForValue) {
      if (objectBuilder_ == null) {
        object_ = builderForValue.build();
      } else {
        objectBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     */
    public Builder mergeObject(studio.o7.octopus.sdk.v1.Object value) {
      if (objectBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          object_ != null &&
          object_ != studio.o7.octopus.sdk.v1.Object.getDefaultInstance()) {
          getObjectBuilder().mergeFrom(value);
        } else {
          object_ = value;
        }
      } else {
        objectBuilder_.mergeFrom(value);
      }
      if (object_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     */
    public Builder clearObject() {
      bitField0_ = (bitField0_ & ~0x00000001);
      object_ = null;
      if (objectBuilder_ != null) {
        objectBuilder_.dispose();
        objectBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     */
    public studio.o7.octopus.sdk.v1.Object.Builder getObjectBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetObjectFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     */
    public studio.o7.octopus.sdk.v1.ObjectOrBuilder getObjectOrBuilder() {
      if (objectBuilder_ != null) {
        return objectBuilder_.getMessageOrBuilder();
      } else {
        return object_ == null ?
            studio.o7.octopus.sdk.v1.Object.getDefaultInstance() : object_;
      }
    }
    /**
     * <pre>
     * The affected object.
     * </pre>
     *
     * <code>.octopus_sdk.v1.Object object = 1 [json_name = "object"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.Object, studio.o7.octopus.sdk.v1.Object.Builder, studio.o7.octopus.sdk.v1.ObjectOrBuilder> 
        internalGetObjectFieldBuilder() {
      if (objectBuilder_ == null) {
        objectBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            studio.o7.octopus.sdk.v1.Object, studio.o7.octopus.sdk.v1.Object.Builder, studio.o7.octopus.sdk.v1.ObjectOrBuilder>(
                getObject(),
                getParentForChildren(),
                isClean());
        object_ = null;
      }
      return objectBuilder_;
    }

    private java.lang.Object callId_ = "";
    /**
     * <pre>
     * Unique ID for this event call (useful for tracking).
     * </pre>
     *
     * <code>string call_id = 2 [json_name = "callId"];</code>
     * @return The callId.
     */
    public java.lang.String getCallId() {
      java.lang.Object ref = callId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        callId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique ID for this event call (useful for tracking).
     * </pre>
     *
     * <code>string call_id = 2 [json_name = "callId"];</code>
     * @return The bytes for callId.
     */
    public com.google.protobuf.ByteString
        getCallIdBytes() {
      java.lang.Object ref = callId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        callId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique ID for this event call (useful for tracking).
     * </pre>
     *
     * <code>string call_id = 2 [json_name = "callId"];</code>
     * @param value The callId to set.
     * @return This builder for chaining.
     */
    public Builder setCallId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      callId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID for this event call (useful for tracking).
     * </pre>
     *
     * <code>string call_id = 2 [json_name = "callId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCallId() {
      callId_ = getDefaultInstance().getCallId();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique ID for this event call (useful for tracking).
     * </pre>
     *
     * <code>string call_id = 2 [json_name = "callId"];</code>
     * @param value The bytes for callId to set.
     * @return This builder for chaining.
     */
    public Builder setCallIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      callId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:octopus_sdk.v1.EventCall)
  }

  // @@protoc_insertion_point(class_scope:octopus_sdk.v1.EventCall)
  private static final studio.o7.octopus.sdk.v1.EventCall DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studio.o7.octopus.sdk.v1.EventCall();
  }

  public static studio.o7.octopus.sdk.v1.EventCall getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EventCall>
      PARSER = new com.google.protobuf.AbstractParser<EventCall>() {
    @java.lang.Override
    public EventCall parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EventCall> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EventCall> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public studio.o7.octopus.sdk.v1.EventCall getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

