// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

/**
 * <pre>
 * *
 * Filters and options for `Get` RPC.
 * </pre>
 *
 * Protobuf type {@code octopus_sdk.v1.GetRequest}
 */
@com.google.protobuf.Generated
public final class GetRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:octopus_sdk.v1.GetRequest)
    GetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "GetRequest");
  }
  // Use GetRequest.newBuilder() to construct.
  private GetRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetRequest() {
    keyPattern_ = "";
    dataFilter_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studio.o7.octopus.sdk.v1.GetRequest.class, studio.o7.octopus.sdk.v1.GetRequest.Builder.class);
  }

  private int bitField0_;
  public static final int KEY_PATTERN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object keyPattern_ = "";
  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The keyPattern.
   */
  @java.lang.Override
  public java.lang.String getKeyPattern() {
    java.lang.Object ref = keyPattern_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyPattern_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The bytes for keyPattern.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyPatternBytes() {
    java.lang.Object ref = keyPattern_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyPattern_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INCLUDE_EXPIRED_FIELD_NUMBER = 2;
  private boolean includeExpired_ = false;
  /**
   * <pre>
   * Whether to include expired objects.
   * </pre>
   *
   * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
   * @return Whether the includeExpired field is set.
   */
  @java.lang.Override
  public boolean hasIncludeExpired() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Whether to include expired objects.
   * </pre>
   *
   * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
   * @return The includeExpired.
   */
  @java.lang.Override
  public boolean getIncludeExpired() {
    return includeExpired_;
  }

  public static final int CREATED_AT_RANGE_START_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp createdAtRangeStart_;
  /**
   * <pre>
   * Start timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
   * @return Whether the createdAtRangeStart field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAtRangeStart() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Start timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
   * @return The createdAtRangeStart.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAtRangeStart() {
    return createdAtRangeStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeStart_;
  }
  /**
   * <pre>
   * Start timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtRangeStartOrBuilder() {
    return createdAtRangeStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeStart_;
  }

  public static final int CREATED_AT_RANGE_END_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp createdAtRangeEnd_;
  /**
   * <pre>
   * End timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
   * @return Whether the createdAtRangeEnd field is set.
   */
  @java.lang.Override
  public boolean hasCreatedAtRangeEnd() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * End timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
   * @return The createdAtRangeEnd.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreatedAtRangeEnd() {
    return createdAtRangeEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeEnd_;
  }
  /**
   * <pre>
   * End timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreatedAtRangeEndOrBuilder() {
    return createdAtRangeEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeEnd_;
  }

  public static final int DATA_FILTER_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dataFilter_ = "";
  /**
   * <pre>
   * Filter by json in data in MongoDB filter similar pattern
   * </pre>
   *
   * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
   * @return Whether the dataFilter field is set.
   */
  @java.lang.Override
  public boolean hasDataFilter() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Filter by json in data in MongoDB filter similar pattern
   * </pre>
   *
   * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
   * @return The dataFilter.
   */
  @java.lang.Override
  public java.lang.String getDataFilter() {
    java.lang.Object ref = dataFilter_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dataFilter_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Filter by json in data in MongoDB filter similar pattern
   * </pre>
   *
   * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
   * @return The bytes for dataFilter.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataFilterBytes() {
    java.lang.Object ref = dataFilter_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dataFilter_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGINATOR_FIELD_NUMBER = 6;
  private studio.o7.octopus.sdk.v1.Paginator paginator_;
  /**
   * <pre>
   * Entry paginator
   * </pre>
   *
   * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
   * @return Whether the paginator field is set.
   */
  @java.lang.Override
  public boolean hasPaginator() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Entry paginator
   * </pre>
   *
   * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
   * @return The paginator.
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.Paginator getPaginator() {
    return paginator_ == null ? studio.o7.octopus.sdk.v1.Paginator.getDefaultInstance() : paginator_;
  }
  /**
   * <pre>
   * Entry paginator
   * </pre>
   *
   * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.PaginatorOrBuilder getPaginatorOrBuilder() {
    return paginator_ == null ? studio.o7.octopus.sdk.v1.Paginator.getDefaultInstance() : paginator_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyPattern_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, keyPattern_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(2, includeExpired_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getCreatedAtRangeStart());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getCreatedAtRangeEnd());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, dataFilter_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(6, getPaginator());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyPattern_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, keyPattern_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, includeExpired_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCreatedAtRangeStart());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getCreatedAtRangeEnd());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, dataFilter_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPaginator());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studio.o7.octopus.sdk.v1.GetRequest)) {
      return super.equals(obj);
    }
    studio.o7.octopus.sdk.v1.GetRequest other = (studio.o7.octopus.sdk.v1.GetRequest) obj;

    if (!getKeyPattern()
        .equals(other.getKeyPattern())) return false;
    if (hasIncludeExpired() != other.hasIncludeExpired()) return false;
    if (hasIncludeExpired()) {
      if (getIncludeExpired()
          != other.getIncludeExpired()) return false;
    }
    if (hasCreatedAtRangeStart() != other.hasCreatedAtRangeStart()) return false;
    if (hasCreatedAtRangeStart()) {
      if (!getCreatedAtRangeStart()
          .equals(other.getCreatedAtRangeStart())) return false;
    }
    if (hasCreatedAtRangeEnd() != other.hasCreatedAtRangeEnd()) return false;
    if (hasCreatedAtRangeEnd()) {
      if (!getCreatedAtRangeEnd()
          .equals(other.getCreatedAtRangeEnd())) return false;
    }
    if (hasDataFilter() != other.hasDataFilter()) return false;
    if (hasDataFilter()) {
      if (!getDataFilter()
          .equals(other.getDataFilter())) return false;
    }
    if (hasPaginator() != other.hasPaginator()) return false;
    if (hasPaginator()) {
      if (!getPaginator()
          .equals(other.getPaginator())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_PATTERN_FIELD_NUMBER;
    hash = (53 * hash) + getKeyPattern().hashCode();
    if (hasIncludeExpired()) {
      hash = (37 * hash) + INCLUDE_EXPIRED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIncludeExpired());
    }
    if (hasCreatedAtRangeStart()) {
      hash = (37 * hash) + CREATED_AT_RANGE_START_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAtRangeStart().hashCode();
    }
    if (hasCreatedAtRangeEnd()) {
      hash = (37 * hash) + CREATED_AT_RANGE_END_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAtRangeEnd().hashCode();
    }
    if (hasDataFilter()) {
      hash = (37 * hash) + DATA_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getDataFilter().hashCode();
    }
    if (hasPaginator()) {
      hash = (37 * hash) + PAGINATOR_FIELD_NUMBER;
      hash = (53 * hash) + getPaginator().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static studio.o7.octopus.sdk.v1.GetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static studio.o7.octopus.sdk.v1.GetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.GetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studio.o7.octopus.sdk.v1.GetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * Filters and options for `Get` RPC.
   * </pre>
   *
   * Protobuf type {@code octopus_sdk.v1.GetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:octopus_sdk.v1.GetRequest)
      studio.o7.octopus.sdk.v1.GetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studio.o7.octopus.sdk.v1.GetRequest.class, studio.o7.octopus.sdk.v1.GetRequest.Builder.class);
    }

    // Construct using studio.o7.octopus.sdk.v1.GetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetCreatedAtRangeStartFieldBuilder();
        internalGetCreatedAtRangeEndFieldBuilder();
        internalGetPaginatorFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      keyPattern_ = "";
      includeExpired_ = false;
      createdAtRangeStart_ = null;
      if (createdAtRangeStartBuilder_ != null) {
        createdAtRangeStartBuilder_.dispose();
        createdAtRangeStartBuilder_ = null;
      }
      createdAtRangeEnd_ = null;
      if (createdAtRangeEndBuilder_ != null) {
        createdAtRangeEndBuilder_.dispose();
        createdAtRangeEndBuilder_ = null;
      }
      dataFilter_ = "";
      paginator_ = null;
      if (paginatorBuilder_ != null) {
        paginatorBuilder_.dispose();
        paginatorBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetRequest_descriptor;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.GetRequest getDefaultInstanceForType() {
      return studio.o7.octopus.sdk.v1.GetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.GetRequest build() {
      studio.o7.octopus.sdk.v1.GetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.GetRequest buildPartial() {
      studio.o7.octopus.sdk.v1.GetRequest result = new studio.o7.octopus.sdk.v1.GetRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(studio.o7.octopus.sdk.v1.GetRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.keyPattern_ = keyPattern_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.includeExpired_ = includeExpired_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.createdAtRangeStart_ = createdAtRangeStartBuilder_ == null
            ? createdAtRangeStart_
            : createdAtRangeStartBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.createdAtRangeEnd_ = createdAtRangeEndBuilder_ == null
            ? createdAtRangeEnd_
            : createdAtRangeEndBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.dataFilter_ = dataFilter_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.paginator_ = paginatorBuilder_ == null
            ? paginator_
            : paginatorBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studio.o7.octopus.sdk.v1.GetRequest) {
        return mergeFrom((studio.o7.octopus.sdk.v1.GetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studio.o7.octopus.sdk.v1.GetRequest other) {
      if (other == studio.o7.octopus.sdk.v1.GetRequest.getDefaultInstance()) return this;
      if (!other.getKeyPattern().isEmpty()) {
        keyPattern_ = other.keyPattern_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasIncludeExpired()) {
        setIncludeExpired(other.getIncludeExpired());
      }
      if (other.hasCreatedAtRangeStart()) {
        mergeCreatedAtRangeStart(other.getCreatedAtRangeStart());
      }
      if (other.hasCreatedAtRangeEnd()) {
        mergeCreatedAtRangeEnd(other.getCreatedAtRangeEnd());
      }
      if (other.hasDataFilter()) {
        dataFilter_ = other.dataFilter_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.hasPaginator()) {
        mergePaginator(other.getPaginator());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              keyPattern_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              includeExpired_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  internalGetCreatedAtRangeStartFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetCreatedAtRangeEndFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              dataFilter_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetPaginatorFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object keyPattern_ = "";
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @return The keyPattern.
     */
    public java.lang.String getKeyPattern() {
      java.lang.Object ref = keyPattern_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyPattern_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @return The bytes for keyPattern.
     */
    public com.google.protobuf.ByteString
        getKeyPatternBytes() {
      java.lang.Object ref = keyPattern_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyPattern_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @param value The keyPattern to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPattern(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      keyPattern_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyPattern() {
      keyPattern_ = getDefaultInstance().getKeyPattern();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @param value The bytes for keyPattern to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPatternBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      keyPattern_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean includeExpired_ ;
    /**
     * <pre>
     * Whether to include expired objects.
     * </pre>
     *
     * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
     * @return Whether the includeExpired field is set.
     */
    @java.lang.Override
    public boolean hasIncludeExpired() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Whether to include expired objects.
     * </pre>
     *
     * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
     * @return The includeExpired.
     */
    @java.lang.Override
    public boolean getIncludeExpired() {
      return includeExpired_;
    }
    /**
     * <pre>
     * Whether to include expired objects.
     * </pre>
     *
     * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
     * @param value The includeExpired to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeExpired(boolean value) {

      includeExpired_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether to include expired objects.
     * </pre>
     *
     * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeExpired() {
      bitField0_ = (bitField0_ & ~0x00000002);
      includeExpired_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAtRangeStart_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtRangeStartBuilder_;
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     * @return Whether the createdAtRangeStart field is set.
     */
    public boolean hasCreatedAtRangeStart() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     * @return The createdAtRangeStart.
     */
    public com.google.protobuf.Timestamp getCreatedAtRangeStart() {
      if (createdAtRangeStartBuilder_ == null) {
        return createdAtRangeStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeStart_;
      } else {
        return createdAtRangeStartBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     */
    public Builder setCreatedAtRangeStart(com.google.protobuf.Timestamp value) {
      if (createdAtRangeStartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAtRangeStart_ = value;
      } else {
        createdAtRangeStartBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     */
    public Builder setCreatedAtRangeStart(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtRangeStartBuilder_ == null) {
        createdAtRangeStart_ = builderForValue.build();
      } else {
        createdAtRangeStartBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     */
    public Builder mergeCreatedAtRangeStart(com.google.protobuf.Timestamp value) {
      if (createdAtRangeStartBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          createdAtRangeStart_ != null &&
          createdAtRangeStart_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtRangeStartBuilder().mergeFrom(value);
        } else {
          createdAtRangeStart_ = value;
        }
      } else {
        createdAtRangeStartBuilder_.mergeFrom(value);
      }
      if (createdAtRangeStart_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     */
    public Builder clearCreatedAtRangeStart() {
      bitField0_ = (bitField0_ & ~0x00000004);
      createdAtRangeStart_ = null;
      if (createdAtRangeStartBuilder_ != null) {
        createdAtRangeStartBuilder_.dispose();
        createdAtRangeStartBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtRangeStartBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetCreatedAtRangeStartFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtRangeStartOrBuilder() {
      if (createdAtRangeStartBuilder_ != null) {
        return createdAtRangeStartBuilder_.getMessageOrBuilder();
      } else {
        return createdAtRangeStart_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeStart_;
      }
    }
    /**
     * <pre>
     * Start timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCreatedAtRangeStartFieldBuilder() {
      if (createdAtRangeStartBuilder_ == null) {
        createdAtRangeStartBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAtRangeStart(),
                getParentForChildren(),
                isClean());
        createdAtRangeStart_ = null;
      }
      return createdAtRangeStartBuilder_;
    }

    private com.google.protobuf.Timestamp createdAtRangeEnd_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtRangeEndBuilder_;
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     * @return Whether the createdAtRangeEnd field is set.
     */
    public boolean hasCreatedAtRangeEnd() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     * @return The createdAtRangeEnd.
     */
    public com.google.protobuf.Timestamp getCreatedAtRangeEnd() {
      if (createdAtRangeEndBuilder_ == null) {
        return createdAtRangeEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeEnd_;
      } else {
        return createdAtRangeEndBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     */
    public Builder setCreatedAtRangeEnd(com.google.protobuf.Timestamp value) {
      if (createdAtRangeEndBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAtRangeEnd_ = value;
      } else {
        createdAtRangeEndBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     */
    public Builder setCreatedAtRangeEnd(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtRangeEndBuilder_ == null) {
        createdAtRangeEnd_ = builderForValue.build();
      } else {
        createdAtRangeEndBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     */
    public Builder mergeCreatedAtRangeEnd(com.google.protobuf.Timestamp value) {
      if (createdAtRangeEndBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          createdAtRangeEnd_ != null &&
          createdAtRangeEnd_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreatedAtRangeEndBuilder().mergeFrom(value);
        } else {
          createdAtRangeEnd_ = value;
        }
      } else {
        createdAtRangeEndBuilder_.mergeFrom(value);
      }
      if (createdAtRangeEnd_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     */
    public Builder clearCreatedAtRangeEnd() {
      bitField0_ = (bitField0_ & ~0x00000008);
      createdAtRangeEnd_ = null;
      if (createdAtRangeEndBuilder_ != null) {
        createdAtRangeEndBuilder_.dispose();
        createdAtRangeEndBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtRangeEndBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetCreatedAtRangeEndFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtRangeEndOrBuilder() {
      if (createdAtRangeEndBuilder_ != null) {
        return createdAtRangeEndBuilder_.getMessageOrBuilder();
      } else {
        return createdAtRangeEnd_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAtRangeEnd_;
      }
    }
    /**
     * <pre>
     * End timestamp to filter creation time.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetCreatedAtRangeEndFieldBuilder() {
      if (createdAtRangeEndBuilder_ == null) {
        createdAtRangeEndBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAtRangeEnd(),
                getParentForChildren(),
                isClean());
        createdAtRangeEnd_ = null;
      }
      return createdAtRangeEndBuilder_;
    }

    private java.lang.Object dataFilter_ = "";
    /**
     * <pre>
     * Filter by json in data in MongoDB filter similar pattern
     * </pre>
     *
     * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
     * @return Whether the dataFilter field is set.
     */
    public boolean hasDataFilter() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Filter by json in data in MongoDB filter similar pattern
     * </pre>
     *
     * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
     * @return The dataFilter.
     */
    public java.lang.String getDataFilter() {
      java.lang.Object ref = dataFilter_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dataFilter_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Filter by json in data in MongoDB filter similar pattern
     * </pre>
     *
     * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
     * @return The bytes for dataFilter.
     */
    public com.google.protobuf.ByteString
        getDataFilterBytes() {
      java.lang.Object ref = dataFilter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dataFilter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Filter by json in data in MongoDB filter similar pattern
     * </pre>
     *
     * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
     * @param value The dataFilter to set.
     * @return This builder for chaining.
     */
    public Builder setDataFilter(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dataFilter_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter by json in data in MongoDB filter similar pattern
     * </pre>
     *
     * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDataFilter() {
      dataFilter_ = getDefaultInstance().getDataFilter();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Filter by json in data in MongoDB filter similar pattern
     * </pre>
     *
     * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
     * @param value The bytes for dataFilter to set.
     * @return This builder for chaining.
     */
    public Builder setDataFilterBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dataFilter_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private studio.o7.octopus.sdk.v1.Paginator paginator_;
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.Paginator, studio.o7.octopus.sdk.v1.Paginator.Builder, studio.o7.octopus.sdk.v1.PaginatorOrBuilder> paginatorBuilder_;
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     * @return Whether the paginator field is set.
     */
    public boolean hasPaginator() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     * @return The paginator.
     */
    public studio.o7.octopus.sdk.v1.Paginator getPaginator() {
      if (paginatorBuilder_ == null) {
        return paginator_ == null ? studio.o7.octopus.sdk.v1.Paginator.getDefaultInstance() : paginator_;
      } else {
        return paginatorBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     */
    public Builder setPaginator(studio.o7.octopus.sdk.v1.Paginator value) {
      if (paginatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paginator_ = value;
      } else {
        paginatorBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     */
    public Builder setPaginator(
        studio.o7.octopus.sdk.v1.Paginator.Builder builderForValue) {
      if (paginatorBuilder_ == null) {
        paginator_ = builderForValue.build();
      } else {
        paginatorBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     */
    public Builder mergePaginator(studio.o7.octopus.sdk.v1.Paginator value) {
      if (paginatorBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          paginator_ != null &&
          paginator_ != studio.o7.octopus.sdk.v1.Paginator.getDefaultInstance()) {
          getPaginatorBuilder().mergeFrom(value);
        } else {
          paginator_ = value;
        }
      } else {
        paginatorBuilder_.mergeFrom(value);
      }
      if (paginator_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     */
    public Builder clearPaginator() {
      bitField0_ = (bitField0_ & ~0x00000020);
      paginator_ = null;
      if (paginatorBuilder_ != null) {
        paginatorBuilder_.dispose();
        paginatorBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     */
    public studio.o7.octopus.sdk.v1.Paginator.Builder getPaginatorBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetPaginatorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     */
    public studio.o7.octopus.sdk.v1.PaginatorOrBuilder getPaginatorOrBuilder() {
      if (paginatorBuilder_ != null) {
        return paginatorBuilder_.getMessageOrBuilder();
      } else {
        return paginator_ == null ?
            studio.o7.octopus.sdk.v1.Paginator.getDefaultInstance() : paginator_;
      }
    }
    /**
     * <pre>
     * Entry paginator
     * </pre>
     *
     * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.Paginator, studio.o7.octopus.sdk.v1.Paginator.Builder, studio.o7.octopus.sdk.v1.PaginatorOrBuilder> 
        internalGetPaginatorFieldBuilder() {
      if (paginatorBuilder_ == null) {
        paginatorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            studio.o7.octopus.sdk.v1.Paginator, studio.o7.octopus.sdk.v1.Paginator.Builder, studio.o7.octopus.sdk.v1.PaginatorOrBuilder>(
                getPaginator(),
                getParentForChildren(),
                isClean());
        paginator_ = null;
      }
      return paginatorBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:octopus_sdk.v1.GetRequest)
  }

  // @@protoc_insertion_point(class_scope:octopus_sdk.v1.GetRequest)
  private static final studio.o7.octopus.sdk.v1.GetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studio.o7.octopus.sdk.v1.GetRequest();
  }

  public static studio.o7.octopus.sdk.v1.GetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetRequest>() {
    @java.lang.Override
    public GetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public studio.o7.octopus.sdk.v1.GetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

