// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

/**
 * <pre>
 * *
 * Result of `Get` RPC.
 * </pre>
 *
 * Protobuf type {@code octopus_sdk.v1.GetResponse}
 */
@com.google.protobuf.Generated
public final class GetResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:octopus_sdk.v1.GetResponse)
    GetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "GetResponse");
  }
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
    entries_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studio.o7.octopus.sdk.v1.GetResponse.class, studio.o7.octopus.sdk.v1.GetResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ENTRIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<studio.o7.octopus.sdk.v1.Entry> entries_;
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public java.util.List<studio.o7.octopus.sdk.v1.Entry> getEntriesList() {
    return entries_;
  }
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends studio.o7.octopus.sdk.v1.EntryOrBuilder> 
      getEntriesOrBuilderList() {
    return entries_;
  }
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public int getEntriesCount() {
    return entries_.size();
  }
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.Entry getEntries(int index) {
    return entries_.get(index);
  }
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.EntryOrBuilder getEntriesOrBuilder(
      int index) {
    return entries_.get(index);
  }

  public static final int PAGE_INFO_FIELD_NUMBER = 2;
  private studio.o7.octopus.sdk.v1.PageInfo pageInfo_;
  /**
   * <pre>
   * Page information's about the cursor.
   * </pre>
   *
   * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
   * @return Whether the pageInfo field is set.
   */
  @java.lang.Override
  public boolean hasPageInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Page information's about the cursor.
   * </pre>
   *
   * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
   * @return The pageInfo.
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.PageInfo getPageInfo() {
    return pageInfo_ == null ? studio.o7.octopus.sdk.v1.PageInfo.getDefaultInstance() : pageInfo_;
  }
  /**
   * <pre>
   * Page information's about the cursor.
   * </pre>
   *
   * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.PageInfoOrBuilder getPageInfoOrBuilder() {
    return pageInfo_ == null ? studio.o7.octopus.sdk.v1.PageInfo.getDefaultInstance() : pageInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entries_.size(); i++) {
      output.writeMessage(1, entries_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getPageInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entries_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPageInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studio.o7.octopus.sdk.v1.GetResponse)) {
      return super.equals(obj);
    }
    studio.o7.octopus.sdk.v1.GetResponse other = (studio.o7.octopus.sdk.v1.GetResponse) obj;

    if (!getEntriesList()
        .equals(other.getEntriesList())) return false;
    if (hasPageInfo() != other.hasPageInfo()) return false;
    if (hasPageInfo()) {
      if (!getPageInfo()
          .equals(other.getPageInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntriesCount() > 0) {
      hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
      hash = (53 * hash) + getEntriesList().hashCode();
    }
    if (hasPageInfo()) {
      hash = (37 * hash) + PAGE_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getPageInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static studio.o7.octopus.sdk.v1.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static studio.o7.octopus.sdk.v1.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studio.o7.octopus.sdk.v1.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * Result of `Get` RPC.
   * </pre>
   *
   * Protobuf type {@code octopus_sdk.v1.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:octopus_sdk.v1.GetResponse)
      studio.o7.octopus.sdk.v1.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studio.o7.octopus.sdk.v1.GetResponse.class, studio.o7.octopus.sdk.v1.GetResponse.Builder.class);
    }

    // Construct using studio.o7.octopus.sdk.v1.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetEntriesFieldBuilder();
        internalGetPageInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
      } else {
        entries_ = null;
        entriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      pageInfo_ = null;
      if (pageInfoBuilder_ != null) {
        pageInfoBuilder_.dispose();
        pageInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_GetResponse_descriptor;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.GetResponse getDefaultInstanceForType() {
      return studio.o7.octopus.sdk.v1.GetResponse.getDefaultInstance();
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.GetResponse build() {
      studio.o7.octopus.sdk.v1.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.GetResponse buildPartial() {
      studio.o7.octopus.sdk.v1.GetResponse result = new studio.o7.octopus.sdk.v1.GetResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(studio.o7.octopus.sdk.v1.GetResponse result) {
      if (entriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          entries_ = java.util.Collections.unmodifiableList(entries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entries_ = entries_;
      } else {
        result.entries_ = entriesBuilder_.build();
      }
    }

    private void buildPartial0(studio.o7.octopus.sdk.v1.GetResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.pageInfo_ = pageInfoBuilder_ == null
            ? pageInfo_
            : pageInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studio.o7.octopus.sdk.v1.GetResponse) {
        return mergeFrom((studio.o7.octopus.sdk.v1.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studio.o7.octopus.sdk.v1.GetResponse other) {
      if (other == studio.o7.octopus.sdk.v1.GetResponse.getDefaultInstance()) return this;
      if (entriesBuilder_ == null) {
        if (!other.entries_.isEmpty()) {
          if (entries_.isEmpty()) {
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntriesIsMutable();
            entries_.addAll(other.entries_);
          }
          onChanged();
        }
      } else {
        if (!other.entries_.isEmpty()) {
          if (entriesBuilder_.isEmpty()) {
            entriesBuilder_.dispose();
            entriesBuilder_ = null;
            entries_ = other.entries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entriesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetEntriesFieldBuilder() : null;
          } else {
            entriesBuilder_.addAllMessages(other.entries_);
          }
        }
      }
      if (other.hasPageInfo()) {
        mergePageInfo(other.getPageInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              studio.o7.octopus.sdk.v1.Entry m =
                  input.readMessage(
                      studio.o7.octopus.sdk.v1.Entry.parser(),
                      extensionRegistry);
              if (entriesBuilder_ == null) {
                ensureEntriesIsMutable();
                entries_.add(m);
              } else {
                entriesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetPageInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<studio.o7.octopus.sdk.v1.Entry> entries_ =
      java.util.Collections.emptyList();
    private void ensureEntriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        entries_ = new java.util.ArrayList<studio.o7.octopus.sdk.v1.Entry>(entries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        studio.o7.octopus.sdk.v1.Entry, studio.o7.octopus.sdk.v1.Entry.Builder, studio.o7.octopus.sdk.v1.EntryOrBuilder> entriesBuilder_;

    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public java.util.List<studio.o7.octopus.sdk.v1.Entry> getEntriesList() {
      if (entriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entries_);
      } else {
        return entriesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public int getEntriesCount() {
      if (entriesBuilder_ == null) {
        return entries_.size();
      } else {
        return entriesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public studio.o7.octopus.sdk.v1.Entry getEntries(int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);
      } else {
        return entriesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder setEntries(
        int index, studio.o7.octopus.sdk.v1.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.set(index, value);
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder setEntries(
        int index, studio.o7.octopus.sdk.v1.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.set(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder addEntries(studio.o7.octopus.sdk.v1.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder addEntries(
        int index, studio.o7.octopus.sdk.v1.Entry value) {
      if (entriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntriesIsMutable();
        entries_.add(index, value);
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder addEntries(
        studio.o7.octopus.sdk.v1.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder addEntries(
        int index, studio.o7.octopus.sdk.v1.Entry.Builder builderForValue) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.add(index, builderForValue.build());
        onChanged();
      } else {
        entriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder addAllEntries(
        java.lang.Iterable<? extends studio.o7.octopus.sdk.v1.Entry> values) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entries_);
        onChanged();
      } else {
        entriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder clearEntries() {
      if (entriesBuilder_ == null) {
        entries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public Builder removeEntries(int index) {
      if (entriesBuilder_ == null) {
        ensureEntriesIsMutable();
        entries_.remove(index);
        onChanged();
      } else {
        entriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public studio.o7.octopus.sdk.v1.Entry.Builder getEntriesBuilder(
        int index) {
      return internalGetEntriesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public studio.o7.octopus.sdk.v1.EntryOrBuilder getEntriesOrBuilder(
        int index) {
      if (entriesBuilder_ == null) {
        return entries_.get(index);  } else {
        return entriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public java.util.List<? extends studio.o7.octopus.sdk.v1.EntryOrBuilder> 
         getEntriesOrBuilderList() {
      if (entriesBuilder_ != null) {
        return entriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entries_);
      }
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public studio.o7.octopus.sdk.v1.Entry.Builder addEntriesBuilder() {
      return internalGetEntriesFieldBuilder().addBuilder(
          studio.o7.octopus.sdk.v1.Entry.getDefaultInstance());
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public studio.o7.octopus.sdk.v1.Entry.Builder addEntriesBuilder(
        int index) {
      return internalGetEntriesFieldBuilder().addBuilder(
          index, studio.o7.octopus.sdk.v1.Entry.getDefaultInstance());
    }
    /**
     * <pre>
     * List of found entries including revision, ID and timestamps.
     * </pre>
     *
     * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
     */
    public java.util.List<studio.o7.octopus.sdk.v1.Entry.Builder> 
         getEntriesBuilderList() {
      return internalGetEntriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        studio.o7.octopus.sdk.v1.Entry, studio.o7.octopus.sdk.v1.Entry.Builder, studio.o7.octopus.sdk.v1.EntryOrBuilder> 
        internalGetEntriesFieldBuilder() {
      if (entriesBuilder_ == null) {
        entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            studio.o7.octopus.sdk.v1.Entry, studio.o7.octopus.sdk.v1.Entry.Builder, studio.o7.octopus.sdk.v1.EntryOrBuilder>(
                entries_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        entries_ = null;
      }
      return entriesBuilder_;
    }

    private studio.o7.octopus.sdk.v1.PageInfo pageInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.PageInfo, studio.o7.octopus.sdk.v1.PageInfo.Builder, studio.o7.octopus.sdk.v1.PageInfoOrBuilder> pageInfoBuilder_;
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     * @return Whether the pageInfo field is set.
     */
    public boolean hasPageInfo() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     * @return The pageInfo.
     */
    public studio.o7.octopus.sdk.v1.PageInfo getPageInfo() {
      if (pageInfoBuilder_ == null) {
        return pageInfo_ == null ? studio.o7.octopus.sdk.v1.PageInfo.getDefaultInstance() : pageInfo_;
      } else {
        return pageInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     */
    public Builder setPageInfo(studio.o7.octopus.sdk.v1.PageInfo value) {
      if (pageInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageInfo_ = value;
      } else {
        pageInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     */
    public Builder setPageInfo(
        studio.o7.octopus.sdk.v1.PageInfo.Builder builderForValue) {
      if (pageInfoBuilder_ == null) {
        pageInfo_ = builderForValue.build();
      } else {
        pageInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     */
    public Builder mergePageInfo(studio.o7.octopus.sdk.v1.PageInfo value) {
      if (pageInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          pageInfo_ != null &&
          pageInfo_ != studio.o7.octopus.sdk.v1.PageInfo.getDefaultInstance()) {
          getPageInfoBuilder().mergeFrom(value);
        } else {
          pageInfo_ = value;
        }
      } else {
        pageInfoBuilder_.mergeFrom(value);
      }
      if (pageInfo_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     */
    public Builder clearPageInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      pageInfo_ = null;
      if (pageInfoBuilder_ != null) {
        pageInfoBuilder_.dispose();
        pageInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     */
    public studio.o7.octopus.sdk.v1.PageInfo.Builder getPageInfoBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetPageInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     */
    public studio.o7.octopus.sdk.v1.PageInfoOrBuilder getPageInfoOrBuilder() {
      if (pageInfoBuilder_ != null) {
        return pageInfoBuilder_.getMessageOrBuilder();
      } else {
        return pageInfo_ == null ?
            studio.o7.octopus.sdk.v1.PageInfo.getDefaultInstance() : pageInfo_;
      }
    }
    /**
     * <pre>
     * Page information's about the cursor.
     * </pre>
     *
     * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.PageInfo, studio.o7.octopus.sdk.v1.PageInfo.Builder, studio.o7.octopus.sdk.v1.PageInfoOrBuilder> 
        internalGetPageInfoFieldBuilder() {
      if (pageInfoBuilder_ == null) {
        pageInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            studio.o7.octopus.sdk.v1.PageInfo, studio.o7.octopus.sdk.v1.PageInfo.Builder, studio.o7.octopus.sdk.v1.PageInfoOrBuilder>(
                getPageInfo(),
                getParentForChildren(),
                isClean());
        pageInfo_ = null;
      }
      return pageInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:octopus_sdk.v1.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:octopus_sdk.v1.GetResponse)
  private static final studio.o7.octopus.sdk.v1.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studio.o7.octopus.sdk.v1.GetResponse();
  }

  public static studio.o7.octopus.sdk.v1.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    @java.lang.Override
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public studio.o7.octopus.sdk.v1.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

