// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The keyPattern.
   */
  java.lang.String getKeyPattern();
  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The bytes for keyPattern.
   */
  com.google.protobuf.ByteString
      getKeyPatternBytes();

  /**
   * <pre>
   * Whether to include expired objects.
   * </pre>
   *
   * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
   * @return Whether the includeExpired field is set.
   */
  boolean hasIncludeExpired();
  /**
   * <pre>
   * Whether to include expired objects.
   * </pre>
   *
   * <code>optional bool include_expired = 2 [json_name = "includeExpired"];</code>
   * @return The includeExpired.
   */
  boolean getIncludeExpired();

  /**
   * <pre>
   * Start timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
   * @return Whether the createdAtRangeStart field is set.
   */
  boolean hasCreatedAtRangeStart();
  /**
   * <pre>
   * Start timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
   * @return The createdAtRangeStart.
   */
  com.google.protobuf.Timestamp getCreatedAtRangeStart();
  /**
   * <pre>
   * Start timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_start = 3 [json_name = "createdAtRangeStart"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtRangeStartOrBuilder();

  /**
   * <pre>
   * End timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
   * @return Whether the createdAtRangeEnd field is set.
   */
  boolean hasCreatedAtRangeEnd();
  /**
   * <pre>
   * End timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
   * @return The createdAtRangeEnd.
   */
  com.google.protobuf.Timestamp getCreatedAtRangeEnd();
  /**
   * <pre>
   * End timestamp to filter creation time.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp created_at_range_end = 4 [json_name = "createdAtRangeEnd"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAtRangeEndOrBuilder();

  /**
   * <pre>
   * Filter by json in data in MongoDB filter similar pattern
   * </pre>
   *
   * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
   * @return Whether the dataFilter field is set.
   */
  boolean hasDataFilter();
  /**
   * <pre>
   * Filter by json in data in MongoDB filter similar pattern
   * </pre>
   *
   * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
   * @return The dataFilter.
   */
  java.lang.String getDataFilter();
  /**
   * <pre>
   * Filter by json in data in MongoDB filter similar pattern
   * </pre>
   *
   * <code>optional string data_filter = 5 [json_name = "dataFilter"];</code>
   * @return The bytes for dataFilter.
   */
  com.google.protobuf.ByteString
      getDataFilterBytes();

  /**
   * <pre>
   * Entry paginator
   * </pre>
   *
   * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
   * @return Whether the paginator field is set.
   */
  boolean hasPaginator();
  /**
   * <pre>
   * Entry paginator
   * </pre>
   *
   * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
   * @return The paginator.
   */
  studio.o7.octopus.sdk.v1.Paginator getPaginator();
  /**
   * <pre>
   * Entry paginator
   * </pre>
   *
   * <code>optional .octopus_sdk.v1.Paginator paginator = 6 [json_name = "paginator"];</code>
   */
  studio.o7.octopus.sdk.v1.PaginatorOrBuilder getPaginatorOrBuilder();
}
