// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface GetResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.GetResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  java.util.List<studio.o7.octopus.sdk.v1.Entry> 
      getEntriesList();
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  studio.o7.octopus.sdk.v1.Entry getEntries(int index);
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  int getEntriesCount();
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  java.util.List<? extends studio.o7.octopus.sdk.v1.EntryOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <pre>
   * List of found entries including revision, ID and timestamps.
   * </pre>
   *
   * <code>repeated .octopus_sdk.v1.Entry entries = 1 [json_name = "entries"];</code>
   */
  studio.o7.octopus.sdk.v1.EntryOrBuilder getEntriesOrBuilder(
      int index);

  /**
   * <pre>
   * Page information's about the cursor.
   * </pre>
   *
   * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
   * @return Whether the pageInfo field is set.
   */
  boolean hasPageInfo();
  /**
   * <pre>
   * Page information's about the cursor.
   * </pre>
   *
   * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
   * @return The pageInfo.
   */
  studio.o7.octopus.sdk.v1.PageInfo getPageInfo();
  /**
   * <pre>
   * Page information's about the cursor.
   * </pre>
   *
   * <code>.octopus_sdk.v1.PageInfo page_info = 2 [json_name = "pageInfo"];</code>
   */
  studio.o7.octopus.sdk.v1.PageInfoOrBuilder getPageInfoOrBuilder();
}
