// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

/**
 * <pre>
 * *
 * Message type for the listen stream.
 * </pre>
 *
 * Protobuf type {@code octopus_sdk.v1.ListenMessage}
 */
@com.google.protobuf.Generated
public final class ListenMessage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:octopus_sdk.v1.ListenMessage)
    ListenMessageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ListenMessage");
  }
  // Use ListenMessage.newBuilder() to construct.
  private ListenMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListenMessage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studio.o7.octopus.sdk.v1.ListenMessage.class, studio.o7.octopus.sdk.v1.ListenMessage.Builder.class);
  }

  private int msgCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object msg_;
  public enum MsgCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    CALLBACK(1),
    REGISTER(2),
    MSG_NOT_SET(0);
    private final int value;
    private MsgCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgCase valueOf(int value) {
      return forNumber(value);
    }

    public static MsgCase forNumber(int value) {
      switch (value) {
        case 1: return CALLBACK;
        case 2: return REGISTER;
        case 0: return MSG_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MsgCase
  getMsgCase() {
    return MsgCase.forNumber(
        msgCase_);
  }

  public static final int CALLBACK_FIELD_NUMBER = 1;
  /**
   * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
   * @return Whether the callback field is set.
   */
  @java.lang.Override
  public boolean hasCallback() {
    return msgCase_ == 1;
  }
  /**
   * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
   * @return The callback.
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.EventCall getCallback() {
    if (msgCase_ == 1) {
       return (studio.o7.octopus.sdk.v1.EventCall) msg_;
    }
    return studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance();
  }
  /**
   * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.EventCallOrBuilder getCallbackOrBuilder() {
    if (msgCase_ == 1) {
       return (studio.o7.octopus.sdk.v1.EventCall) msg_;
    }
    return studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance();
  }

  public static final int REGISTER_FIELD_NUMBER = 2;
  /**
   * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
   * @return Whether the register field is set.
   */
  @java.lang.Override
  public boolean hasRegister() {
    return msgCase_ == 2;
  }
  /**
   * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
   * @return The register.
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.ListenRegister getRegister() {
    if (msgCase_ == 2) {
       return (studio.o7.octopus.sdk.v1.ListenRegister) msg_;
    }
    return studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance();
  }
  /**
   * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
   */
  @java.lang.Override
  public studio.o7.octopus.sdk.v1.ListenRegisterOrBuilder getRegisterOrBuilder() {
    if (msgCase_ == 2) {
       return (studio.o7.octopus.sdk.v1.ListenRegister) msg_;
    }
    return studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (msgCase_ == 1) {
      output.writeMessage(1, (studio.o7.octopus.sdk.v1.EventCall) msg_);
    }
    if (msgCase_ == 2) {
      output.writeMessage(2, (studio.o7.octopus.sdk.v1.ListenRegister) msg_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (msgCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (studio.o7.octopus.sdk.v1.EventCall) msg_);
    }
    if (msgCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (studio.o7.octopus.sdk.v1.ListenRegister) msg_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studio.o7.octopus.sdk.v1.ListenMessage)) {
      return super.equals(obj);
    }
    studio.o7.octopus.sdk.v1.ListenMessage other = (studio.o7.octopus.sdk.v1.ListenMessage) obj;

    if (!getMsgCase().equals(other.getMsgCase())) return false;
    switch (msgCase_) {
      case 1:
        if (!getCallback()
            .equals(other.getCallback())) return false;
        break;
      case 2:
        if (!getRegister()
            .equals(other.getRegister())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (msgCase_) {
      case 1:
        hash = (37 * hash) + CALLBACK_FIELD_NUMBER;
        hash = (53 * hash) + getCallback().hashCode();
        break;
      case 2:
        hash = (37 * hash) + REGISTER_FIELD_NUMBER;
        hash = (53 * hash) + getRegister().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static studio.o7.octopus.sdk.v1.ListenMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static studio.o7.octopus.sdk.v1.ListenMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.ListenMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studio.o7.octopus.sdk.v1.ListenMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * Message type for the listen stream.
   * </pre>
   *
   * Protobuf type {@code octopus_sdk.v1.ListenMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:octopus_sdk.v1.ListenMessage)
      studio.o7.octopus.sdk.v1.ListenMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studio.o7.octopus.sdk.v1.ListenMessage.class, studio.o7.octopus.sdk.v1.ListenMessage.Builder.class);
    }

    // Construct using studio.o7.octopus.sdk.v1.ListenMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (callbackBuilder_ != null) {
        callbackBuilder_.clear();
      }
      if (registerBuilder_ != null) {
        registerBuilder_.clear();
      }
      msgCase_ = 0;
      msg_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenMessage_descriptor;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenMessage getDefaultInstanceForType() {
      return studio.o7.octopus.sdk.v1.ListenMessage.getDefaultInstance();
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenMessage build() {
      studio.o7.octopus.sdk.v1.ListenMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenMessage buildPartial() {
      studio.o7.octopus.sdk.v1.ListenMessage result = new studio.o7.octopus.sdk.v1.ListenMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(studio.o7.octopus.sdk.v1.ListenMessage result) {
      int from_bitField0_ = bitField0_;
    }

    private void buildPartialOneofs(studio.o7.octopus.sdk.v1.ListenMessage result) {
      result.msgCase_ = msgCase_;
      result.msg_ = this.msg_;
      if (msgCase_ == 1 &&
          callbackBuilder_ != null) {
        result.msg_ = callbackBuilder_.build();
      }
      if (msgCase_ == 2 &&
          registerBuilder_ != null) {
        result.msg_ = registerBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studio.o7.octopus.sdk.v1.ListenMessage) {
        return mergeFrom((studio.o7.octopus.sdk.v1.ListenMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studio.o7.octopus.sdk.v1.ListenMessage other) {
      if (other == studio.o7.octopus.sdk.v1.ListenMessage.getDefaultInstance()) return this;
      switch (other.getMsgCase()) {
        case CALLBACK: {
          mergeCallback(other.getCallback());
          break;
        }
        case REGISTER: {
          mergeRegister(other.getRegister());
          break;
        }
        case MSG_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetCallbackFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 1;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetRegisterFieldBuilder().getBuilder(),
                  extensionRegistry);
              msgCase_ = 2;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int msgCase_ = 0;
    private java.lang.Object msg_;
    public MsgCase
        getMsgCase() {
      return MsgCase.forNumber(
          msgCase_);
    }

    public Builder clearMsg() {
      msgCase_ = 0;
      msg_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.EventCall, studio.o7.octopus.sdk.v1.EventCall.Builder, studio.o7.octopus.sdk.v1.EventCallOrBuilder> callbackBuilder_;
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     * @return Whether the callback field is set.
     */
    @java.lang.Override
    public boolean hasCallback() {
      return msgCase_ == 1;
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     * @return The callback.
     */
    @java.lang.Override
    public studio.o7.octopus.sdk.v1.EventCall getCallback() {
      if (callbackBuilder_ == null) {
        if (msgCase_ == 1) {
          return (studio.o7.octopus.sdk.v1.EventCall) msg_;
        }
        return studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance();
      } else {
        if (msgCase_ == 1) {
          return callbackBuilder_.getMessage();
        }
        return studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance();
      }
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     */
    public Builder setCallback(studio.o7.octopus.sdk.v1.EventCall value) {
      if (callbackBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        callbackBuilder_.setMessage(value);
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     */
    public Builder setCallback(
        studio.o7.octopus.sdk.v1.EventCall.Builder builderForValue) {
      if (callbackBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        callbackBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     */
    public Builder mergeCallback(studio.o7.octopus.sdk.v1.EventCall value) {
      if (callbackBuilder_ == null) {
        if (msgCase_ == 1 &&
            msg_ != studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance()) {
          msg_ = studio.o7.octopus.sdk.v1.EventCall.newBuilder((studio.o7.octopus.sdk.v1.EventCall) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 1) {
          callbackBuilder_.mergeFrom(value);
        } else {
          callbackBuilder_.setMessage(value);
        }
      }
      msgCase_ = 1;
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     */
    public Builder clearCallback() {
      if (callbackBuilder_ == null) {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 1) {
          msgCase_ = 0;
          msg_ = null;
        }
        callbackBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     */
    public studio.o7.octopus.sdk.v1.EventCall.Builder getCallbackBuilder() {
      return internalGetCallbackFieldBuilder().getBuilder();
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     */
    @java.lang.Override
    public studio.o7.octopus.sdk.v1.EventCallOrBuilder getCallbackOrBuilder() {
      if ((msgCase_ == 1) && (callbackBuilder_ != null)) {
        return callbackBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 1) {
          return (studio.o7.octopus.sdk.v1.EventCall) msg_;
        }
        return studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance();
      }
    }
    /**
     * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.EventCall, studio.o7.octopus.sdk.v1.EventCall.Builder, studio.o7.octopus.sdk.v1.EventCallOrBuilder> 
        internalGetCallbackFieldBuilder() {
      if (callbackBuilder_ == null) {
        if (!(msgCase_ == 1)) {
          msg_ = studio.o7.octopus.sdk.v1.EventCall.getDefaultInstance();
        }
        callbackBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            studio.o7.octopus.sdk.v1.EventCall, studio.o7.octopus.sdk.v1.EventCall.Builder, studio.o7.octopus.sdk.v1.EventCallOrBuilder>(
                (studio.o7.octopus.sdk.v1.EventCall) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 1;
      onChanged();
      return callbackBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.ListenRegister, studio.o7.octopus.sdk.v1.ListenRegister.Builder, studio.o7.octopus.sdk.v1.ListenRegisterOrBuilder> registerBuilder_;
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     * @return Whether the register field is set.
     */
    @java.lang.Override
    public boolean hasRegister() {
      return msgCase_ == 2;
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     * @return The register.
     */
    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenRegister getRegister() {
      if (registerBuilder_ == null) {
        if (msgCase_ == 2) {
          return (studio.o7.octopus.sdk.v1.ListenRegister) msg_;
        }
        return studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance();
      } else {
        if (msgCase_ == 2) {
          return registerBuilder_.getMessage();
        }
        return studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance();
      }
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     */
    public Builder setRegister(studio.o7.octopus.sdk.v1.ListenRegister value) {
      if (registerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        msg_ = value;
        onChanged();
      } else {
        registerBuilder_.setMessage(value);
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     */
    public Builder setRegister(
        studio.o7.octopus.sdk.v1.ListenRegister.Builder builderForValue) {
      if (registerBuilder_ == null) {
        msg_ = builderForValue.build();
        onChanged();
      } else {
        registerBuilder_.setMessage(builderForValue.build());
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     */
    public Builder mergeRegister(studio.o7.octopus.sdk.v1.ListenRegister value) {
      if (registerBuilder_ == null) {
        if (msgCase_ == 2 &&
            msg_ != studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance()) {
          msg_ = studio.o7.octopus.sdk.v1.ListenRegister.newBuilder((studio.o7.octopus.sdk.v1.ListenRegister) msg_)
              .mergeFrom(value).buildPartial();
        } else {
          msg_ = value;
        }
        onChanged();
      } else {
        if (msgCase_ == 2) {
          registerBuilder_.mergeFrom(value);
        } else {
          registerBuilder_.setMessage(value);
        }
      }
      msgCase_ = 2;
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     */
    public Builder clearRegister() {
      if (registerBuilder_ == null) {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
          onChanged();
        }
      } else {
        if (msgCase_ == 2) {
          msgCase_ = 0;
          msg_ = null;
        }
        registerBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     */
    public studio.o7.octopus.sdk.v1.ListenRegister.Builder getRegisterBuilder() {
      return internalGetRegisterFieldBuilder().getBuilder();
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     */
    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenRegisterOrBuilder getRegisterOrBuilder() {
      if ((msgCase_ == 2) && (registerBuilder_ != null)) {
        return registerBuilder_.getMessageOrBuilder();
      } else {
        if (msgCase_ == 2) {
          return (studio.o7.octopus.sdk.v1.ListenRegister) msg_;
        }
        return studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance();
      }
    }
    /**
     * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        studio.o7.octopus.sdk.v1.ListenRegister, studio.o7.octopus.sdk.v1.ListenRegister.Builder, studio.o7.octopus.sdk.v1.ListenRegisterOrBuilder> 
        internalGetRegisterFieldBuilder() {
      if (registerBuilder_ == null) {
        if (!(msgCase_ == 2)) {
          msg_ = studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance();
        }
        registerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            studio.o7.octopus.sdk.v1.ListenRegister, studio.o7.octopus.sdk.v1.ListenRegister.Builder, studio.o7.octopus.sdk.v1.ListenRegisterOrBuilder>(
                (studio.o7.octopus.sdk.v1.ListenRegister) msg_,
                getParentForChildren(),
                isClean());
        msg_ = null;
      }
      msgCase_ = 2;
      onChanged();
      return registerBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:octopus_sdk.v1.ListenMessage)
  }

  // @@protoc_insertion_point(class_scope:octopus_sdk.v1.ListenMessage)
  private static final studio.o7.octopus.sdk.v1.ListenMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studio.o7.octopus.sdk.v1.ListenMessage();
  }

  public static studio.o7.octopus.sdk.v1.ListenMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListenMessage>
      PARSER = new com.google.protobuf.AbstractParser<ListenMessage>() {
    @java.lang.Override
    public ListenMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListenMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListenMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public studio.o7.octopus.sdk.v1.ListenMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

