// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface ListenRegisterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.ListenRegister)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The keyPattern.
   */
  java.lang.String getKeyPattern();
  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The bytes for keyPattern.
   */
  com.google.protobuf.ByteString
      getKeyPatternBytes();

  /**
   * <pre>
   * Priority of the registration (e.g. determines event order; lower is later).
   * </pre>
   *
   * <code>int32 priority = 2 [json_name = "priority"];</code>
   * @return The priority.
   */
  int getPriority();
}
