// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface ListenMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.ListenMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
   * @return Whether the callback field is set.
   */
  boolean hasCallback();
  /**
   * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
   * @return The callback.
   */
  studio.o7.octopus.sdk.v1.EventCall getCallback();
  /**
   * <code>.octopus_sdk.v1.EventCall callback = 1 [json_name = "callback"];</code>
   */
  studio.o7.octopus.sdk.v1.EventCallOrBuilder getCallbackOrBuilder();

  /**
   * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
   * @return Whether the register field is set.
   */
  boolean hasRegister();
  /**
   * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
   * @return The register.
   */
  studio.o7.octopus.sdk.v1.ListenRegister getRegister();
  /**
   * <code>.octopus_sdk.v1.ListenRegister register = 2 [json_name = "register"];</code>
   */
  studio.o7.octopus.sdk.v1.ListenRegisterOrBuilder getRegisterOrBuilder();

  studio.o7.octopus.sdk.v1.ListenMessage.MsgCase getMsgCase();
}
