// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

/**
 * <pre>
 * *
 * Registers the stream for real-time updates on specific
 * key pattern.
 * </pre>
 *
 * Protobuf type {@code octopus_sdk.v1.ListenRegister}
 */
@com.google.protobuf.Generated
public final class ListenRegister extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:octopus_sdk.v1.ListenRegister)
    ListenRegisterOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "ListenRegister");
  }
  // Use ListenRegister.newBuilder() to construct.
  private ListenRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListenRegister() {
    keyPattern_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenRegister_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenRegister_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studio.o7.octopus.sdk.v1.ListenRegister.class, studio.o7.octopus.sdk.v1.ListenRegister.Builder.class);
  }

  public static final int KEY_PATTERN_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object keyPattern_ = "";
  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The keyPattern.
   */
  @java.lang.Override
  public java.lang.String getKeyPattern() {
    java.lang.Object ref = keyPattern_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyPattern_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Pattern to match keys. Supports wildcards:
   * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
   * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
   * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
   * </pre>
   *
   * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
   * @return The bytes for keyPattern.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyPatternBytes() {
    java.lang.Object ref = keyPattern_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyPattern_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRIORITY_FIELD_NUMBER = 2;
  private int priority_ = 0;
  /**
   * <pre>
   * Priority of the registration (e.g. determines event order; lower is later).
   * </pre>
   *
   * <code>int32 priority = 2 [json_name = "priority"];</code>
   * @return The priority.
   */
  @java.lang.Override
  public int getPriority() {
    return priority_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyPattern_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, keyPattern_);
    }
    if (priority_ != 0) {
      output.writeInt32(2, priority_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(keyPattern_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, keyPattern_);
    }
    if (priority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, priority_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studio.o7.octopus.sdk.v1.ListenRegister)) {
      return super.equals(obj);
    }
    studio.o7.octopus.sdk.v1.ListenRegister other = (studio.o7.octopus.sdk.v1.ListenRegister) obj;

    if (!getKeyPattern()
        .equals(other.getKeyPattern())) return false;
    if (getPriority()
        != other.getPriority()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_PATTERN_FIELD_NUMBER;
    hash = (53 * hash) + getKeyPattern().hashCode();
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getPriority();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static studio.o7.octopus.sdk.v1.ListenRegister parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static studio.o7.octopus.sdk.v1.ListenRegister parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.ListenRegister parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studio.o7.octopus.sdk.v1.ListenRegister prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * Registers the stream for real-time updates on specific
   * key pattern.
   * </pre>
   *
   * Protobuf type {@code octopus_sdk.v1.ListenRegister}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:octopus_sdk.v1.ListenRegister)
      studio.o7.octopus.sdk.v1.ListenRegisterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenRegister_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studio.o7.octopus.sdk.v1.ListenRegister.class, studio.o7.octopus.sdk.v1.ListenRegister.Builder.class);
    }

    // Construct using studio.o7.octopus.sdk.v1.ListenRegister.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      keyPattern_ = "";
      priority_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_ListenRegister_descriptor;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenRegister getDefaultInstanceForType() {
      return studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance();
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenRegister build() {
      studio.o7.octopus.sdk.v1.ListenRegister result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.ListenRegister buildPartial() {
      studio.o7.octopus.sdk.v1.ListenRegister result = new studio.o7.octopus.sdk.v1.ListenRegister(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(studio.o7.octopus.sdk.v1.ListenRegister result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.keyPattern_ = keyPattern_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.priority_ = priority_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studio.o7.octopus.sdk.v1.ListenRegister) {
        return mergeFrom((studio.o7.octopus.sdk.v1.ListenRegister)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studio.o7.octopus.sdk.v1.ListenRegister other) {
      if (other == studio.o7.octopus.sdk.v1.ListenRegister.getDefaultInstance()) return this;
      if (!other.getKeyPattern().isEmpty()) {
        keyPattern_ = other.keyPattern_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getPriority() != 0) {
        setPriority(other.getPriority());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              keyPattern_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              priority_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object keyPattern_ = "";
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @return The keyPattern.
     */
    public java.lang.String getKeyPattern() {
      java.lang.Object ref = keyPattern_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyPattern_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @return The bytes for keyPattern.
     */
    public com.google.protobuf.ByteString
        getKeyPatternBytes() {
      java.lang.Object ref = keyPattern_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyPattern_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @param value The keyPattern to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPattern(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      keyPattern_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyPattern() {
      keyPattern_ = getDefaultInstance().getKeyPattern();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pattern to match keys. Supports wildcards:
     * *  — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
     * &gt;  — matches one or more tokens until the end, e.g., "foo.&gt;" matches "foo", "foo.bar", "foo.bar.baz", etc.
     * Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
     * </pre>
     *
     * <code>string key_pattern = 1 [json_name = "keyPattern"];</code>
     * @param value The bytes for keyPattern to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPatternBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      keyPattern_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int priority_ ;
    /**
     * <pre>
     * Priority of the registration (e.g. determines event order; lower is later).
     * </pre>
     *
     * <code>int32 priority = 2 [json_name = "priority"];</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }
    /**
     * <pre>
     * Priority of the registration (e.g. determines event order; lower is later).
     * </pre>
     *
     * <code>int32 priority = 2 [json_name = "priority"];</code>
     * @param value The priority to set.
     * @return This builder for chaining.
     */
    public Builder setPriority(int value) {

      priority_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Priority of the registration (e.g. determines event order; lower is later).
     * </pre>
     *
     * <code>int32 priority = 2 [json_name = "priority"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPriority() {
      bitField0_ = (bitField0_ & ~0x00000002);
      priority_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:octopus_sdk.v1.ListenRegister)
  }

  // @@protoc_insertion_point(class_scope:octopus_sdk.v1.ListenRegister)
  private static final studio.o7.octopus.sdk.v1.ListenRegister DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studio.o7.octopus.sdk.v1.ListenRegister();
  }

  public static studio.o7.octopus.sdk.v1.ListenRegister getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListenRegister>
      PARSER = new com.google.protobuf.AbstractParser<ListenRegister>() {
    @java.lang.Override
    public ListenRegister parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListenRegister> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListenRegister> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public studio.o7.octopus.sdk.v1.ListenRegister getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

