// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface ObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.Object)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique key identifying the object.
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <pre>
   * Unique key identifying the object.
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <pre>
   * Flexible JSON-like data structure.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <pre>
   * Flexible JSON-like data structure.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
   * @return The data.
   */
  com.google.protobuf.Struct getData();
  /**
   * <pre>
   * Flexible JSON-like data structure.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
   */
  com.google.protobuf.StructOrBuilder getDataOrBuilder();

  /**
   * <pre>
   * Timestamp when the object should no longer be visible by default.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
   * @return Whether the expiredAt field is set.
   */
  boolean hasExpiredAt();
  /**
   * <pre>
   * Timestamp when the object should no longer be visible by default.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
   * @return The expiredAt.
   */
  com.google.protobuf.Timestamp getExpiredAt();
  /**
   * <pre>
   * Timestamp when the object should no longer be visible by default.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiredAtOrBuilder();

  /**
   * <pre>
   * Timestamp when the object should be permanently deleted.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
   * @return Whether the deletedAt field is set.
   */
  boolean hasDeletedAt();
  /**
   * <pre>
   * Timestamp when the object should be permanently deleted.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
   * @return The deletedAt.
   */
  com.google.protobuf.Timestamp getDeletedAt();
  /**
   * <pre>
   * Timestamp when the object should be permanently deleted.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder();
}
