// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

/**
 * <pre>
 * *
 * Represents a flexible data object.
 * </pre>
 *
 * Protobuf type {@code octopus_sdk.v1.Object}
 */
@com.google.protobuf.Generated
public final class Object extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:octopus_sdk.v1.Object)
    ObjectOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "Object");
  }
  // Use Object.newBuilder() to construct.
  private Object(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Object() {
    key_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_Object_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_Object_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studio.o7.octopus.sdk.v1.Object.class, studio.o7.octopus.sdk.v1.Object.Builder.class);
  }

  private int bitField0_;
  public static final int KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object key_ = "";
  /**
   * <pre>
   * Unique key identifying the object.
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The key.
   */
  @java.lang.Override
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Unique key identifying the object.
   * </pre>
   *
   * <code>string key = 1 [json_name = "key"];</code>
   * @return The bytes for key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.Struct data_;
  /**
   * <pre>
   * Flexible JSON-like data structure.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
   * @return Whether the data field is set.
   */
  @java.lang.Override
  public boolean hasData() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Flexible JSON-like data structure.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
   * @return The data.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getData() {
    return data_ == null ? com.google.protobuf.Struct.getDefaultInstance() : data_;
  }
  /**
   * <pre>
   * Flexible JSON-like data structure.
   * </pre>
   *
   * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getDataOrBuilder() {
    return data_ == null ? com.google.protobuf.Struct.getDefaultInstance() : data_;
  }

  public static final int EXPIRED_AT_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp expiredAt_;
  /**
   * <pre>
   * Timestamp when the object should no longer be visible by default.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
   * @return Whether the expiredAt field is set.
   */
  @java.lang.Override
  public boolean hasExpiredAt() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Timestamp when the object should no longer be visible by default.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
   * @return The expiredAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpiredAt() {
    return expiredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
  }
  /**
   * <pre>
   * Timestamp when the object should no longer be visible by default.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpiredAtOrBuilder() {
    return expiredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
  }

  public static final int DELETED_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp deletedAt_;
  /**
   * <pre>
   * Timestamp when the object should be permanently deleted.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
   * @return Whether the deletedAt field is set.
   */
  @java.lang.Override
  public boolean hasDeletedAt() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Timestamp when the object should be permanently deleted.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
   * @return The deletedAt.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getDeletedAt() {
    return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
  }
  /**
   * <pre>
   * Timestamp when the object should be permanently deleted.
   * </pre>
   *
   * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder() {
    return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, key_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getData());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getExpiredAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getDeletedAt());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(key_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, key_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getData());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getExpiredAt());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDeletedAt());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studio.o7.octopus.sdk.v1.Object)) {
      return super.equals(obj);
    }
    studio.o7.octopus.sdk.v1.Object other = (studio.o7.octopus.sdk.v1.Object) obj;

    if (!getKey()
        .equals(other.getKey())) return false;
    if (hasData() != other.hasData()) return false;
    if (hasData()) {
      if (!getData()
          .equals(other.getData())) return false;
    }
    if (hasExpiredAt() != other.hasExpiredAt()) return false;
    if (hasExpiredAt()) {
      if (!getExpiredAt()
          .equals(other.getExpiredAt())) return false;
    }
    if (hasDeletedAt() != other.hasDeletedAt()) return false;
    if (hasDeletedAt()) {
      if (!getDeletedAt()
          .equals(other.getDeletedAt())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    if (hasExpiredAt()) {
      hash = (37 * hash) + EXPIRED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getExpiredAt().hashCode();
    }
    if (hasDeletedAt()) {
      hash = (37 * hash) + DELETED_AT_FIELD_NUMBER;
      hash = (53 * hash) + getDeletedAt().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static studio.o7.octopus.sdk.v1.Object parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static studio.o7.octopus.sdk.v1.Object parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.Object parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studio.o7.octopus.sdk.v1.Object prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * *
   * Represents a flexible data object.
   * </pre>
   *
   * Protobuf type {@code octopus_sdk.v1.Object}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:octopus_sdk.v1.Object)
      studio.o7.octopus.sdk.v1.ObjectOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_Object_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_Object_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studio.o7.octopus.sdk.v1.Object.class, studio.o7.octopus.sdk.v1.Object.Builder.class);
    }

    // Construct using studio.o7.octopus.sdk.v1.Object.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetDataFieldBuilder();
        internalGetExpiredAtFieldBuilder();
        internalGetDeletedAtFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      key_ = "";
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      expiredAt_ = null;
      if (expiredAtBuilder_ != null) {
        expiredAtBuilder_.dispose();
        expiredAtBuilder_ = null;
      }
      deletedAt_ = null;
      if (deletedAtBuilder_ != null) {
        deletedAtBuilder_.dispose();
        deletedAtBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_Object_descriptor;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.Object getDefaultInstanceForType() {
      return studio.o7.octopus.sdk.v1.Object.getDefaultInstance();
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.Object build() {
      studio.o7.octopus.sdk.v1.Object result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.Object buildPartial() {
      studio.o7.octopus.sdk.v1.Object result = new studio.o7.octopus.sdk.v1.Object(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(studio.o7.octopus.sdk.v1.Object result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.key_ = key_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.data_ = dataBuilder_ == null
            ? data_
            : dataBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.expiredAt_ = expiredAtBuilder_ == null
            ? expiredAt_
            : expiredAtBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.deletedAt_ = deletedAtBuilder_ == null
            ? deletedAt_
            : deletedAtBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studio.o7.octopus.sdk.v1.Object) {
        return mergeFrom((studio.o7.octopus.sdk.v1.Object)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studio.o7.octopus.sdk.v1.Object other) {
      if (other == studio.o7.octopus.sdk.v1.Object.getDefaultInstance()) return this;
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      if (other.hasExpiredAt()) {
        mergeExpiredAt(other.getExpiredAt());
      }
      if (other.hasDeletedAt()) {
        mergeDeletedAt(other.getDeletedAt());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              key_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  internalGetDataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  internalGetExpiredAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetDeletedAtFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object key_ = "";
    /**
     * <pre>
     * Unique key identifying the object.
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Unique key identifying the object.
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Unique key identifying the object.
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique key identifying the object.
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      key_ = getDefaultInstance().getKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Unique key identifying the object.
     * </pre>
     *
     * <code>string key = 1 [json_name = "key"];</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      key_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct data_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> dataBuilder_;
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @return Whether the data field is set.
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     * @return The data.
     */
    public com.google.protobuf.Struct getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.google.protobuf.Struct.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    public Builder setData(com.google.protobuf.Struct value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
      } else {
        dataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    public Builder setData(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    public Builder mergeData(com.google.protobuf.Struct value) {
      if (dataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          data_ != null &&
          data_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getDataBuilder().mergeFrom(value);
        } else {
          data_ = value;
        }
      } else {
        dataBuilder_.mergeFrom(value);
      }
      if (data_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    public Builder clearData() {
      bitField0_ = (bitField0_ & ~0x00000002);
      data_ = null;
      if (dataBuilder_ != null) {
        dataBuilder_.dispose();
        dataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    public com.google.protobuf.Struct.Builder getDataBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return internalGetDataFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    public com.google.protobuf.StructOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : data_;
      }
    }
    /**
     * <pre>
     * Flexible JSON-like data structure.
     * </pre>
     *
     * <code>.google.protobuf.Struct data = 2 [json_name = "data"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        internalGetDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }

    private com.google.protobuf.Timestamp expiredAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiredAtBuilder_;
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     * @return Whether the expiredAt field is set.
     */
    public boolean hasExpiredAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     * @return The expiredAt.
     */
    public com.google.protobuf.Timestamp getExpiredAt() {
      if (expiredAtBuilder_ == null) {
        return expiredAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
      } else {
        return expiredAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     */
    public Builder setExpiredAt(com.google.protobuf.Timestamp value) {
      if (expiredAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expiredAt_ = value;
      } else {
        expiredAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     */
    public Builder setExpiredAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiredAtBuilder_ == null) {
        expiredAt_ = builderForValue.build();
      } else {
        expiredAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     */
    public Builder mergeExpiredAt(com.google.protobuf.Timestamp value) {
      if (expiredAtBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          expiredAt_ != null &&
          expiredAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getExpiredAtBuilder().mergeFrom(value);
        } else {
          expiredAt_ = value;
        }
      } else {
        expiredAtBuilder_.mergeFrom(value);
      }
      if (expiredAt_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     */
    public Builder clearExpiredAt() {
      bitField0_ = (bitField0_ & ~0x00000004);
      expiredAt_ = null;
      if (expiredAtBuilder_ != null) {
        expiredAtBuilder_.dispose();
        expiredAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiredAtBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return internalGetExpiredAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiredAtOrBuilder() {
      if (expiredAtBuilder_ != null) {
        return expiredAtBuilder_.getMessageOrBuilder();
      } else {
        return expiredAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expiredAt_;
      }
    }
    /**
     * <pre>
     * Timestamp when the object should no longer be visible by default.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp expired_at = 3 [json_name = "expiredAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetExpiredAtFieldBuilder() {
      if (expiredAtBuilder_ == null) {
        expiredAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpiredAt(),
                getParentForChildren(),
                isClean());
        expiredAt_ = null;
      }
      return expiredAtBuilder_;
    }

    private com.google.protobuf.Timestamp deletedAt_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> deletedAtBuilder_;
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     * @return Whether the deletedAt field is set.
     */
    public boolean hasDeletedAt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     * @return The deletedAt.
     */
    public com.google.protobuf.Timestamp getDeletedAt() {
      if (deletedAtBuilder_ == null) {
        return deletedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
      } else {
        return deletedAtBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     */
    public Builder setDeletedAt(com.google.protobuf.Timestamp value) {
      if (deletedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deletedAt_ = value;
      } else {
        deletedAtBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     */
    public Builder setDeletedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (deletedAtBuilder_ == null) {
        deletedAt_ = builderForValue.build();
      } else {
        deletedAtBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     */
    public Builder mergeDeletedAt(com.google.protobuf.Timestamp value) {
      if (deletedAtBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          deletedAt_ != null &&
          deletedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getDeletedAtBuilder().mergeFrom(value);
        } else {
          deletedAt_ = value;
        }
      } else {
        deletedAtBuilder_.mergeFrom(value);
      }
      if (deletedAt_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     */
    public Builder clearDeletedAt() {
      bitField0_ = (bitField0_ & ~0x00000008);
      deletedAt_ = null;
      if (deletedAtBuilder_ != null) {
        deletedAtBuilder_.dispose();
        deletedAtBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getDeletedAtBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetDeletedAtFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDeletedAtOrBuilder() {
      if (deletedAtBuilder_ != null) {
        return deletedAtBuilder_.getMessageOrBuilder();
      } else {
        return deletedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : deletedAt_;
      }
    }
    /**
     * <pre>
     * Timestamp when the object should be permanently deleted.
     * </pre>
     *
     * <code>optional .google.protobuf.Timestamp deleted_at = 4 [json_name = "deletedAt"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        internalGetDeletedAtFieldBuilder() {
      if (deletedAtBuilder_ == null) {
        deletedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDeletedAt(),
                getParentForChildren(),
                isClean());
        deletedAt_ = null;
      }
      return deletedAtBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:octopus_sdk.v1.Object)
  }

  // @@protoc_insertion_point(class_scope:octopus_sdk.v1.Object)
  private static final studio.o7.octopus.sdk.v1.Object DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studio.o7.octopus.sdk.v1.Object();
  }

  public static studio.o7.octopus.sdk.v1.Object getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Object>
      PARSER = new com.google.protobuf.AbstractParser<Object>() {
    @java.lang.Override
    public Object parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Object> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Object> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public studio.o7.octopus.sdk.v1.Object getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

