// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface PageInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.PageInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * current page (1-based)
   * </pre>
   *
   * <code>int32 current_page = 1 [json_name = "currentPage"];</code>
   * @return The currentPage.
   */
  int getCurrentPage();

  /**
   * <pre>
   * current page size
   * </pre>
   *
   * <code>int32 current_page_size = 2 [json_name = "currentPageSize"];</code>
   * @return The currentPageSize.
   */
  int getCurrentPageSize();

  /**
   * <pre>
   * last page number
   * </pre>
   *
   * <code>int32 total_pages = 3 [json_name = "totalPages"];</code>
   * @return The totalPages.
   */
  int getTotalPages();

  /**
   * <pre>
   * total matching items
   * </pre>
   *
   * <code>int64 total_items = 4 [json_name = "totalItems"];</code>
   * @return The totalItems.
   */
  long getTotalItems();

  /**
   * <pre>
   * next page id. null if not present
   * </pre>
   *
   * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
   * @return Whether the nextPage field is set.
   */
  boolean hasNextPage();
  /**
   * <pre>
   * next page id. null if not present
   * </pre>
   *
   * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
   * @return The nextPage.
   */
  int getNextPage();

  /**
   * <pre>
   * previous page id. null if not present
   * </pre>
   *
   * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
   * @return Whether the prevPage field is set.
   */
  boolean hasPrevPage();
  /**
   * <pre>
   * previous page id. null if not present
   * </pre>
   *
   * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
   * @return The prevPage.
   */
  int getPrevPage();
}
