// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

/**
 * Protobuf type {@code octopus_sdk.v1.PageInfo}
 */
@com.google.protobuf.Generated
public final class PageInfo extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:octopus_sdk.v1.PageInfo)
    PageInfoOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 2,
      /* suffix= */ "",
      "PageInfo");
  }
  // Use PageInfo.newBuilder() to construct.
  private PageInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PageInfo() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_PageInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_PageInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            studio.o7.octopus.sdk.v1.PageInfo.class, studio.o7.octopus.sdk.v1.PageInfo.Builder.class);
  }

  private int bitField0_;
  public static final int CURRENT_PAGE_FIELD_NUMBER = 1;
  private int currentPage_ = 0;
  /**
   * <pre>
   * current page (1-based)
   * </pre>
   *
   * <code>int32 current_page = 1 [json_name = "currentPage"];</code>
   * @return The currentPage.
   */
  @java.lang.Override
  public int getCurrentPage() {
    return currentPage_;
  }

  public static final int CURRENT_PAGE_SIZE_FIELD_NUMBER = 2;
  private int currentPageSize_ = 0;
  /**
   * <pre>
   * current page size
   * </pre>
   *
   * <code>int32 current_page_size = 2 [json_name = "currentPageSize"];</code>
   * @return The currentPageSize.
   */
  @java.lang.Override
  public int getCurrentPageSize() {
    return currentPageSize_;
  }

  public static final int TOTAL_PAGES_FIELD_NUMBER = 3;
  private int totalPages_ = 0;
  /**
   * <pre>
   * last page number
   * </pre>
   *
   * <code>int32 total_pages = 3 [json_name = "totalPages"];</code>
   * @return The totalPages.
   */
  @java.lang.Override
  public int getTotalPages() {
    return totalPages_;
  }

  public static final int TOTAL_ITEMS_FIELD_NUMBER = 4;
  private long totalItems_ = 0L;
  /**
   * <pre>
   * total matching items
   * </pre>
   *
   * <code>int64 total_items = 4 [json_name = "totalItems"];</code>
   * @return The totalItems.
   */
  @java.lang.Override
  public long getTotalItems() {
    return totalItems_;
  }

  public static final int NEXT_PAGE_FIELD_NUMBER = 5;
  private int nextPage_ = 0;
  /**
   * <pre>
   * next page id. null if not present
   * </pre>
   *
   * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
   * @return Whether the nextPage field is set.
   */
  @java.lang.Override
  public boolean hasNextPage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * next page id. null if not present
   * </pre>
   *
   * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
   * @return The nextPage.
   */
  @java.lang.Override
  public int getNextPage() {
    return nextPage_;
  }

  public static final int PREV_PAGE_FIELD_NUMBER = 6;
  private int prevPage_ = 0;
  /**
   * <pre>
   * previous page id. null if not present
   * </pre>
   *
   * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
   * @return Whether the prevPage field is set.
   */
  @java.lang.Override
  public boolean hasPrevPage() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * previous page id. null if not present
   * </pre>
   *
   * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
   * @return The prevPage.
   */
  @java.lang.Override
  public int getPrevPage() {
    return prevPage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentPage_ != 0) {
      output.writeInt32(1, currentPage_);
    }
    if (currentPageSize_ != 0) {
      output.writeInt32(2, currentPageSize_);
    }
    if (totalPages_ != 0) {
      output.writeInt32(3, totalPages_);
    }
    if (totalItems_ != 0L) {
      output.writeInt64(4, totalItems_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(5, nextPage_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(6, prevPage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentPage_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, currentPage_);
    }
    if (currentPageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, currentPageSize_);
    }
    if (totalPages_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, totalPages_);
    }
    if (totalItems_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalItems_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, nextPage_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, prevPage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof studio.o7.octopus.sdk.v1.PageInfo)) {
      return super.equals(obj);
    }
    studio.o7.octopus.sdk.v1.PageInfo other = (studio.o7.octopus.sdk.v1.PageInfo) obj;

    if (getCurrentPage()
        != other.getCurrentPage()) return false;
    if (getCurrentPageSize()
        != other.getCurrentPageSize()) return false;
    if (getTotalPages()
        != other.getTotalPages()) return false;
    if (getTotalItems()
        != other.getTotalItems()) return false;
    if (hasNextPage() != other.hasNextPage()) return false;
    if (hasNextPage()) {
      if (getNextPage()
          != other.getNextPage()) return false;
    }
    if (hasPrevPage() != other.hasPrevPage()) return false;
    if (hasPrevPage()) {
      if (getPrevPage()
          != other.getPrevPage()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentPage();
    hash = (37 * hash) + CURRENT_PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentPageSize();
    hash = (37 * hash) + TOTAL_PAGES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalPages();
    hash = (37 * hash) + TOTAL_ITEMS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalItems());
    if (hasNextPage()) {
      hash = (37 * hash) + NEXT_PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getNextPage();
    }
    if (hasPrevPage()) {
      hash = (37 * hash) + PREV_PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPrevPage();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static studio.o7.octopus.sdk.v1.PageInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static studio.o7.octopus.sdk.v1.PageInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static studio.o7.octopus.sdk.v1.PageInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(studio.o7.octopus.sdk.v1.PageInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code octopus_sdk.v1.PageInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:octopus_sdk.v1.PageInfo)
      studio.o7.octopus.sdk.v1.PageInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_PageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_PageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              studio.o7.octopus.sdk.v1.PageInfo.class, studio.o7.octopus.sdk.v1.PageInfo.Builder.class);
    }

    // Construct using studio.o7.octopus.sdk.v1.PageInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      currentPage_ = 0;
      currentPageSize_ = 0;
      totalPages_ = 0;
      totalItems_ = 0L;
      nextPage_ = 0;
      prevPage_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return studio.o7.octopus.sdk.v1.Api.internal_static_octopus_sdk_v1_PageInfo_descriptor;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.PageInfo getDefaultInstanceForType() {
      return studio.o7.octopus.sdk.v1.PageInfo.getDefaultInstance();
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.PageInfo build() {
      studio.o7.octopus.sdk.v1.PageInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public studio.o7.octopus.sdk.v1.PageInfo buildPartial() {
      studio.o7.octopus.sdk.v1.PageInfo result = new studio.o7.octopus.sdk.v1.PageInfo(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(studio.o7.octopus.sdk.v1.PageInfo result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.currentPage_ = currentPage_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.currentPageSize_ = currentPageSize_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.totalPages_ = totalPages_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.totalItems_ = totalItems_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.nextPage_ = nextPage_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.prevPage_ = prevPage_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof studio.o7.octopus.sdk.v1.PageInfo) {
        return mergeFrom((studio.o7.octopus.sdk.v1.PageInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(studio.o7.octopus.sdk.v1.PageInfo other) {
      if (other == studio.o7.octopus.sdk.v1.PageInfo.getDefaultInstance()) return this;
      if (other.getCurrentPage() != 0) {
        setCurrentPage(other.getCurrentPage());
      }
      if (other.getCurrentPageSize() != 0) {
        setCurrentPageSize(other.getCurrentPageSize());
      }
      if (other.getTotalPages() != 0) {
        setTotalPages(other.getTotalPages());
      }
      if (other.getTotalItems() != 0L) {
        setTotalItems(other.getTotalItems());
      }
      if (other.hasNextPage()) {
        setNextPage(other.getNextPage());
      }
      if (other.hasPrevPage()) {
        setPrevPage(other.getPrevPage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              currentPage_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              currentPageSize_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              totalPages_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              totalItems_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              nextPage_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              prevPage_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int currentPage_ ;
    /**
     * <pre>
     * current page (1-based)
     * </pre>
     *
     * <code>int32 current_page = 1 [json_name = "currentPage"];</code>
     * @return The currentPage.
     */
    @java.lang.Override
    public int getCurrentPage() {
      return currentPage_;
    }
    /**
     * <pre>
     * current page (1-based)
     * </pre>
     *
     * <code>int32 current_page = 1 [json_name = "currentPage"];</code>
     * @param value The currentPage to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPage(int value) {

      currentPage_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * current page (1-based)
     * </pre>
     *
     * <code>int32 current_page = 1 [json_name = "currentPage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      currentPage_ = 0;
      onChanged();
      return this;
    }

    private int currentPageSize_ ;
    /**
     * <pre>
     * current page size
     * </pre>
     *
     * <code>int32 current_page_size = 2 [json_name = "currentPageSize"];</code>
     * @return The currentPageSize.
     */
    @java.lang.Override
    public int getCurrentPageSize() {
      return currentPageSize_;
    }
    /**
     * <pre>
     * current page size
     * </pre>
     *
     * <code>int32 current_page_size = 2 [json_name = "currentPageSize"];</code>
     * @param value The currentPageSize to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentPageSize(int value) {

      currentPageSize_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * current page size
     * </pre>
     *
     * <code>int32 current_page_size = 2 [json_name = "currentPageSize"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentPageSize() {
      bitField0_ = (bitField0_ & ~0x00000002);
      currentPageSize_ = 0;
      onChanged();
      return this;
    }

    private int totalPages_ ;
    /**
     * <pre>
     * last page number
     * </pre>
     *
     * <code>int32 total_pages = 3 [json_name = "totalPages"];</code>
     * @return The totalPages.
     */
    @java.lang.Override
    public int getTotalPages() {
      return totalPages_;
    }
    /**
     * <pre>
     * last page number
     * </pre>
     *
     * <code>int32 total_pages = 3 [json_name = "totalPages"];</code>
     * @param value The totalPages to set.
     * @return This builder for chaining.
     */
    public Builder setTotalPages(int value) {

      totalPages_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * last page number
     * </pre>
     *
     * <code>int32 total_pages = 3 [json_name = "totalPages"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalPages() {
      bitField0_ = (bitField0_ & ~0x00000004);
      totalPages_ = 0;
      onChanged();
      return this;
    }

    private long totalItems_ ;
    /**
     * <pre>
     * total matching items
     * </pre>
     *
     * <code>int64 total_items = 4 [json_name = "totalItems"];</code>
     * @return The totalItems.
     */
    @java.lang.Override
    public long getTotalItems() {
      return totalItems_;
    }
    /**
     * <pre>
     * total matching items
     * </pre>
     *
     * <code>int64 total_items = 4 [json_name = "totalItems"];</code>
     * @param value The totalItems to set.
     * @return This builder for chaining.
     */
    public Builder setTotalItems(long value) {

      totalItems_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * total matching items
     * </pre>
     *
     * <code>int64 total_items = 4 [json_name = "totalItems"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalItems() {
      bitField0_ = (bitField0_ & ~0x00000008);
      totalItems_ = 0L;
      onChanged();
      return this;
    }

    private int nextPage_ ;
    /**
     * <pre>
     * next page id. null if not present
     * </pre>
     *
     * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
     * @return Whether the nextPage field is set.
     */
    @java.lang.Override
    public boolean hasNextPage() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * next page id. null if not present
     * </pre>
     *
     * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
     * @return The nextPage.
     */
    @java.lang.Override
    public int getNextPage() {
      return nextPage_;
    }
    /**
     * <pre>
     * next page id. null if not present
     * </pre>
     *
     * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
     * @param value The nextPage to set.
     * @return This builder for chaining.
     */
    public Builder setNextPage(int value) {

      nextPage_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * next page id. null if not present
     * </pre>
     *
     * <code>optional int32 next_page = 5 [json_name = "nextPage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNextPage() {
      bitField0_ = (bitField0_ & ~0x00000010);
      nextPage_ = 0;
      onChanged();
      return this;
    }

    private int prevPage_ ;
    /**
     * <pre>
     * previous page id. null if not present
     * </pre>
     *
     * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
     * @return Whether the prevPage field is set.
     */
    @java.lang.Override
    public boolean hasPrevPage() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <pre>
     * previous page id. null if not present
     * </pre>
     *
     * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
     * @return The prevPage.
     */
    @java.lang.Override
    public int getPrevPage() {
      return prevPage_;
    }
    /**
     * <pre>
     * previous page id. null if not present
     * </pre>
     *
     * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
     * @param value The prevPage to set.
     * @return This builder for chaining.
     */
    public Builder setPrevPage(int value) {

      prevPage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * previous page id. null if not present
     * </pre>
     *
     * <code>optional int32 prev_page = 6 [json_name = "prevPage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPrevPage() {
      bitField0_ = (bitField0_ & ~0x00000020);
      prevPage_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:octopus_sdk.v1.PageInfo)
  }

  // @@protoc_insertion_point(class_scope:octopus_sdk.v1.PageInfo)
  private static final studio.o7.octopus.sdk.v1.PageInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new studio.o7.octopus.sdk.v1.PageInfo();
  }

  public static studio.o7.octopus.sdk.v1.PageInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PageInfo>
      PARSER = new com.google.protobuf.AbstractParser<PageInfo>() {
    @java.lang.Override
    public PageInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PageInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PageInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public studio.o7.octopus.sdk.v1.PageInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

