// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: v1/api.proto
// Protobuf Java Version: 4.33.2

package studio.o7.octopus.sdk.v1;

@com.google.protobuf.Generated
public interface PaginatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:octopus_sdk.v1.Paginator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 1-based page index (page=1 is first page)
   * </pre>
   *
   * <code>int32 page = 1 [json_name = "page"];</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   * Number of items to return.
   * </pre>
   *
   * <code>int32 page_size = 2 [json_name = "pageSize"];</code>
   * @return The pageSize.
   */
  int getPageSize();
}
