// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/api.proto

package octopusv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Represents a flexible data object.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique key identifying the object.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Flexible JSON-like data structure.
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Timestamp when the object should no longer be visible by default.
	ExpiredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt,proto3,oneof" json:"expired_at,omitempty"`
	// Timestamp when the object should be permanently deleted.
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Object) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Object) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Object) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// *
// A versioned object with metadata from database.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The underlying object.
	Object *Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Entry creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Revision number, incremented on every update.
	Revision int64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// Unique identifier for this entry.
	Id            string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
// Filters and options for `Get` RPC.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pattern to match keys. Supports wildcards:
	//   - — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
	//     >  — matches one or more tokens until the end, e.g., "foo.>" matches "foo", "foo.bar", "foo.bar.baz", etc.
	//
	// Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
	KeyPattern string `protobuf:"bytes,1,opt,name=key_pattern,json=keyPattern,proto3" json:"key_pattern,omitempty"`
	// Whether to include expired objects.
	IncludeExpired *bool `protobuf:"varint,2,opt,name=include_expired,json=includeExpired,proto3,oneof" json:"include_expired,omitempty"`
	// Start timestamp to filter creation time.
	CreatedAtRangeStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at_range_start,json=createdAtRangeStart,proto3,oneof" json:"created_at_range_start,omitempty"`
	// End timestamp to filter creation time.
	CreatedAtRangeEnd *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at_range_end,json=createdAtRangeEnd,proto3,oneof" json:"created_at_range_end,omitempty"`
	// Filter by json in data in MongoDB filter similar pattern
	DataFilter *string `protobuf:"bytes,5,opt,name=data_filter,json=dataFilter,proto3,oneof" json:"data_filter,omitempty"`
	// Entry paginator
	Paginator     *Paginator `protobuf:"bytes,6,opt,name=paginator,proto3,oneof" json:"paginator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKeyPattern() string {
	if x != nil {
		return x.KeyPattern
	}
	return ""
}

func (x *GetRequest) GetIncludeExpired() bool {
	if x != nil && x.IncludeExpired != nil {
		return *x.IncludeExpired
	}
	return false
}

func (x *GetRequest) GetCreatedAtRangeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtRangeStart
	}
	return nil
}

func (x *GetRequest) GetCreatedAtRangeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtRangeEnd
	}
	return nil
}

func (x *GetRequest) GetDataFilter() string {
	if x != nil && x.DataFilter != nil {
		return *x.DataFilter
	}
	return ""
}

func (x *GetRequest) GetPaginator() *Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

// *
// Paginator for database entry cursor-pagination.
type Paginator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based page index (page=1 is first page)
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Number of items to return.
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paginator) Reset() {
	*x = Paginator{}
	mi := &file_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paginator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paginator) ProtoMessage() {}

func (x *Paginator) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paginator.ProtoReflect.Descriptor instead.
func (*Paginator) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *Paginator) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Paginator) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                               // current page (1-based)
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // current page size
	TotalPages    int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"` // last page number
	TotalItems    int64                  `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"` // total matching items
	NextPage      *int32                 `protobuf:"varint,5,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"` // next page id. null if not present
	PrevPage      *int32                 `protobuf:"varint,6,opt,name=prev_page,json=prevPage,proto3,oneof" json:"prev_page,omitempty"` // previous page id. null if not present
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PageInfo) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PageInfo) GetNextPage() int32 {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return 0
}

func (x *PageInfo) GetPrevPage() int32 {
	if x != nil && x.PrevPage != nil {
		return *x.PrevPage
	}
	return 0
}

// *
// Result of `Get` RPC.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of found entries including revision, ID and timestamps.
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Page information's about the cursor.
	PageInfo      *PageInfo `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *GetResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// *
// Message type for the listen stream.
type ListenMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ListenMessage_Callback
	//	*ListenMessage_Register
	Msg           isListenMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenMessage) Reset() {
	*x = ListenMessage{}
	mi := &file_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenMessage) ProtoMessage() {}

func (x *ListenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenMessage.ProtoReflect.Descriptor instead.
func (*ListenMessage) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *ListenMessage) GetMsg() isListenMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ListenMessage) GetCallback() *EventCall {
	if x != nil {
		if x, ok := x.Msg.(*ListenMessage_Callback); ok {
			return x.Callback
		}
	}
	return nil
}

func (x *ListenMessage) GetRegister() *ListenRegister {
	if x != nil {
		if x, ok := x.Msg.(*ListenMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

type isListenMessage_Msg interface {
	isListenMessage_Msg()
}

type ListenMessage_Callback struct {
	Callback *EventCall `protobuf:"bytes,1,opt,name=callback,proto3,oneof"`
}

type ListenMessage_Register struct {
	Register *ListenRegister `protobuf:"bytes,2,opt,name=register,proto3,oneof"`
}

func (*ListenMessage_Callback) isListenMessage_Msg() {}

func (*ListenMessage_Register) isListenMessage_Msg() {}

// *
// Represents a event in the stream.
type EventCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The affected object.
	Object *Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Unique ID for this event call (useful for tracking).
	CallId        string `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCall) Reset() {
	*x = EventCall{}
	mi := &file_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCall) ProtoMessage() {}

func (x *EventCall) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCall.ProtoReflect.Descriptor instead.
func (*EventCall) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *EventCall) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *EventCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// *
// Registers the stream for real-time updates on specific
// key pattern.
type ListenRegister struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pattern to match keys. Supports wildcards:
	//   - — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
	//     >  — matches one or more tokens until the end, e.g., "foo.>" matches "foo", "foo.bar", "foo.bar.baz", etc.
	//
	// Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
	KeyPattern string `protobuf:"bytes,1,opt,name=key_pattern,json=keyPattern,proto3" json:"key_pattern,omitempty"`
	// Priority of the registration (e.g. determines event order; lower is later).
	Priority      int32 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRegister) Reset() {
	*x = ListenRegister{}
	mi := &file_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRegister) ProtoMessage() {}

func (x *ListenRegister) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRegister.ProtoReflect.Descriptor instead.
func (*ListenRegister) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListenRegister) GetKeyPattern() string {
	if x != nil {
		return x.KeyPattern
	}
	return ""
}

func (x *ListenRegister) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_v1_api_proto protoreflect.FileDescriptor

const file_v1_api_proto_rawDesc = "" +
	"\n" +
	"\fv1/api.proto\x12\x0eoctopus_sdk.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\xe5\x01\n" +
	"\x06Object\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x12>\n" +
	"\n" +
	"expired_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiredAt\x88\x01\x01\x12>\n" +
	"\n" +
	"deleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_expired_atB\r\n" +
	"\v_deleted_at\"\x9e\x01\n" +
	"\x05Entry\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.octopus_sdk.v1.ObjectR\x06object\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\xcd\x03\n" +
	"\n" +
	"GetRequest\x12\x1f\n" +
	"\vkey_pattern\x18\x01 \x01(\tR\n" +
	"keyPattern\x12,\n" +
	"\x0finclude_expired\x18\x02 \x01(\bH\x00R\x0eincludeExpired\x88\x01\x01\x12T\n" +
	"\x16created_at_range_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x13createdAtRangeStart\x88\x01\x01\x12P\n" +
	"\x14created_at_range_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x11createdAtRangeEnd\x88\x01\x01\x12$\n" +
	"\vdata_filter\x18\x05 \x01(\tH\x03R\n" +
	"dataFilter\x88\x01\x01\x12<\n" +
	"\tpaginator\x18\x06 \x01(\v2\x19.octopus_sdk.v1.PaginatorH\x04R\tpaginator\x88\x01\x01B\x12\n" +
	"\x10_include_expiredB\x19\n" +
	"\x17_created_at_range_startB\x17\n" +
	"\x15_created_at_range_endB\x0e\n" +
	"\f_data_filterB\f\n" +
	"\n" +
	"_paginator\"<\n" +
	"\tPaginator\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xdd\x01\n" +
	"\bPageInfo\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_items\x18\x04 \x01(\x03R\n" +
	"totalItems\x12 \n" +
	"\tnext_page\x18\x05 \x01(\x05H\x00R\bnextPage\x88\x01\x01\x12 \n" +
	"\tprev_page\x18\x06 \x01(\x05H\x01R\bprevPage\x88\x01\x01B\f\n" +
	"\n" +
	"_next_pageB\f\n" +
	"\n" +
	"_prev_page\"u\n" +
	"\vGetResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.octopus_sdk.v1.EntryR\aentries\x125\n" +
	"\tpage_info\x18\x02 \x01(\v2\x18.octopus_sdk.v1.PageInfoR\bpageInfo\"\x8d\x01\n" +
	"\rListenMessage\x127\n" +
	"\bcallback\x18\x01 \x01(\v2\x19.octopus_sdk.v1.EventCallH\x00R\bcallback\x12<\n" +
	"\bregister\x18\x02 \x01(\v2\x1e.octopus_sdk.v1.ListenRegisterH\x00R\bregisterB\x05\n" +
	"\x03msg\"T\n" +
	"\tEventCall\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.octopus_sdk.v1.ObjectR\x06object\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\"M\n" +
	"\x0eListenRegister\x12\x1f\n" +
	"\vkey_pattern\x18\x01 \x01(\tR\n" +
	"keyPattern\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority2\xc6\x02\n" +
	"\aOctopus\x12S\n" +
	"\x03Get\x12\x1a.octopus_sdk.v1.GetRequest\x1a\x1b.octopus_sdk.v1.GetResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/entries\x12O\n" +
	"\x05Write\x12\x16.octopus_sdk.v1.Object\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/objects\x12M\n" +
	"\x04Call\x12\x16.octopus_sdk.v1.Object\x1a\x15.octopus_sdk.v1.Entry\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/entries\x12F\n" +
	"\x06Listen\x12\x1d.octopus_sdk.v1.ListenMessage\x1a\x19.octopus_sdk.v1.EventCall(\x010\x01BN\n" +
	"\x18studio.o7.octopus.sdk.v1P\x01Z0github.com/o7studios/octopus-sdk/go/v1;octopusv1b\x06proto3"

var (
	file_v1_api_proto_rawDescOnce sync.Once
	file_v1_api_proto_rawDescData []byte
)

func file_v1_api_proto_rawDescGZIP() []byte {
	file_v1_api_proto_rawDescOnce.Do(func() {
		file_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)))
	})
	return file_v1_api_proto_rawDescData
}

var file_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_v1_api_proto_goTypes = []any{
	(*Object)(nil),                // 0: octopus_sdk.v1.Object
	(*Entry)(nil),                 // 1: octopus_sdk.v1.Entry
	(*GetRequest)(nil),            // 2: octopus_sdk.v1.GetRequest
	(*Paginator)(nil),             // 3: octopus_sdk.v1.Paginator
	(*PageInfo)(nil),              // 4: octopus_sdk.v1.PageInfo
	(*GetResponse)(nil),           // 5: octopus_sdk.v1.GetResponse
	(*ListenMessage)(nil),         // 6: octopus_sdk.v1.ListenMessage
	(*EventCall)(nil),             // 7: octopus_sdk.v1.EventCall
	(*ListenRegister)(nil),        // 8: octopus_sdk.v1.ListenRegister
	(*structpb.Struct)(nil),       // 9: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
}
var file_v1_api_proto_depIdxs = []int32{
	9,  // 0: octopus_sdk.v1.Object.data:type_name -> google.protobuf.Struct
	10, // 1: octopus_sdk.v1.Object.expired_at:type_name -> google.protobuf.Timestamp
	10, // 2: octopus_sdk.v1.Object.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: octopus_sdk.v1.Entry.object:type_name -> octopus_sdk.v1.Object
	10, // 4: octopus_sdk.v1.Entry.created_at:type_name -> google.protobuf.Timestamp
	10, // 5: octopus_sdk.v1.GetRequest.created_at_range_start:type_name -> google.protobuf.Timestamp
	10, // 6: octopus_sdk.v1.GetRequest.created_at_range_end:type_name -> google.protobuf.Timestamp
	3,  // 7: octopus_sdk.v1.GetRequest.paginator:type_name -> octopus_sdk.v1.Paginator
	1,  // 8: octopus_sdk.v1.GetResponse.entries:type_name -> octopus_sdk.v1.Entry
	4,  // 9: octopus_sdk.v1.GetResponse.page_info:type_name -> octopus_sdk.v1.PageInfo
	7,  // 10: octopus_sdk.v1.ListenMessage.callback:type_name -> octopus_sdk.v1.EventCall
	8,  // 11: octopus_sdk.v1.ListenMessage.register:type_name -> octopus_sdk.v1.ListenRegister
	0,  // 12: octopus_sdk.v1.EventCall.object:type_name -> octopus_sdk.v1.Object
	2,  // 13: octopus_sdk.v1.Octopus.Get:input_type -> octopus_sdk.v1.GetRequest
	0,  // 14: octopus_sdk.v1.Octopus.Write:input_type -> octopus_sdk.v1.Object
	0,  // 15: octopus_sdk.v1.Octopus.Call:input_type -> octopus_sdk.v1.Object
	6,  // 16: octopus_sdk.v1.Octopus.Listen:input_type -> octopus_sdk.v1.ListenMessage
	5,  // 17: octopus_sdk.v1.Octopus.Get:output_type -> octopus_sdk.v1.GetResponse
	11, // 18: octopus_sdk.v1.Octopus.Write:output_type -> google.protobuf.Empty
	1,  // 19: octopus_sdk.v1.Octopus.Call:output_type -> octopus_sdk.v1.Entry
	7,  // 20: octopus_sdk.v1.Octopus.Listen:output_type -> octopus_sdk.v1.EventCall
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_v1_api_proto_init() }
func file_v1_api_proto_init() {
	if File_v1_api_proto != nil {
		return
	}
	file_v1_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_v1_api_proto_msgTypes[6].OneofWrappers = []any{
		(*ListenMessage_Callback)(nil),
		(*ListenMessage_Register)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_api_proto_goTypes,
		DependencyIndexes: file_v1_api_proto_depIdxs,
		MessageInfos:      file_v1_api_proto_msgTypes,
	}.Build()
	File_v1_api_proto = out.File
	file_v1_api_proto_goTypes = nil
	file_v1_api_proto_depIdxs = nil
}
