// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: v1/api.proto

package octopusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersistanceTarget int32

const (
	PersistanceTarget_UNKNOWN   PersistanceTarget = 0
	PersistanceTarget_PERMANENT PersistanceTarget = 1
	PersistanceTarget_CACHED    PersistanceTarget = 2
)

// Enum value maps for PersistanceTarget.
var (
	PersistanceTarget_name = map[int32]string{
		0: "UNKNOWN",
		1: "PERMANENT",
		2: "CACHED",
	}
	PersistanceTarget_value = map[string]int32{
		"UNKNOWN":   0,
		"PERMANENT": 1,
		"CACHED":    2,
	}
)

func (x PersistanceTarget) Enum() *PersistanceTarget {
	p := new(PersistanceTarget)
	*p = x
	return p
}

func (x PersistanceTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PersistanceTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_api_proto_enumTypes[0].Descriptor()
}

func (PersistanceTarget) Type() protoreflect.EnumType {
	return &file_v1_api_proto_enumTypes[0]
}

func (x PersistanceTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PersistanceTarget.Descriptor instead.
func (PersistanceTarget) EnumDescriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{0}
}

type IndexField_IndexDirection int32

const (
	IndexField_UNKNOWN IndexField_IndexDirection = 0
	IndexField_ASC     IndexField_IndexDirection = 1
	IndexField_DESC    IndexField_IndexDirection = 2
)

// Enum value maps for IndexField_IndexDirection.
var (
	IndexField_IndexDirection_name = map[int32]string{
		0: "UNKNOWN",
		1: "ASC",
		2: "DESC",
	}
	IndexField_IndexDirection_value = map[string]int32{
		"UNKNOWN": 0,
		"ASC":     1,
		"DESC":    2,
	}
)

func (x IndexField_IndexDirection) Enum() *IndexField_IndexDirection {
	p := new(IndexField_IndexDirection)
	*p = x
	return p
}

func (x IndexField_IndexDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexField_IndexDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_api_proto_enumTypes[1].Descriptor()
}

func (IndexField_IndexDirection) Type() protoreflect.EnumType {
	return &file_v1_api_proto_enumTypes[1]
}

func (x IndexField_IndexDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexField_IndexDirection.Descriptor instead.
func (IndexField_IndexDirection) EnumDescriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{9, 0}
}

// *
// Represents a flexible data object.
type Object struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique key identifying the object.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Flexible JSON-like data structure.
	Data *structpb.Struct `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// This will create a copy of this object and increment the current revision number.
	PreservePreviousEntry bool `protobuf:"varint,3,opt,name=preserve_previous_entry,json=preservePreviousEntry,proto3" json:"preserve_previous_entry,omitempty"`
	// Timestamp when the object should no longer be visible by default.
	ExpiredAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expired_at,json=expiredAt,proto3,oneof" json:"expired_at,omitempty"`
	// Timestamp when the object should be permanently deleted.
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	// Optional target for persistance. If not set: default = permanent
	Target        *PersistanceTarget `protobuf:"varint,6,opt,name=target,proto3,enum=octopus_sdk.v1.PersistanceTarget,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Object) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Object) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Object) GetPreservePreviousEntry() bool {
	if x != nil {
		return x.PreservePreviousEntry
	}
	return false
}

func (x *Object) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

func (x *Object) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Object) GetTarget() PersistanceTarget {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return PersistanceTarget_UNKNOWN
}

// *
// A versioned object with metadata from database/cache.
type Entry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The underlying object.
	Object *Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Entry creation timestamp.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Revision number, incremented on every update.
	Revision int64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	// Unique identifier for this entry.
	Id            string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *Entry) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Entry) GetRevision() int64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// *
// Filters and options for `Query` RPC.
type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pattern to match keys. Supports wildcards:
	//   - — matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
	//     >  — matches one or more tokens until the end, e.g., "foo.>" matches "foo", "foo.bar", "foo.bar.baz", etc.
	//
	// Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
	KeyPattern string `protobuf:"bytes,1,opt,name=key_pattern,json=keyPattern,proto3" json:"key_pattern,omitempty"`
	// Whether to include expired objects.
	IncludeExpired *bool `protobuf:"varint,2,opt,name=include_expired,json=includeExpired,proto3,oneof" json:"include_expired,omitempty"`
	// Start timestamp to filter creation time.
	CreatedAtRangeStart *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at_range_start,json=createdAtRangeStart,proto3,oneof" json:"created_at_range_start,omitempty"`
	// End timestamp to filter creation time.
	CreatedAtRangeEnd *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at_range_end,json=createdAtRangeEnd,proto3,oneof" json:"created_at_range_end,omitempty"`
	// Filter by json (use MongoDB filter pattern)
	DataFilter *string `protobuf:"bytes,5,opt,name=data_filter,json=dataFilter,proto3,oneof" json:"data_filter,omitempty"`
	// Sort by json (use MongoDB sort pattern)
	DataSort *string `protobuf:"bytes,6,opt,name=data_sort,json=dataSort,proto3,oneof" json:"data_sort,omitempty"`
	// Entry paginator
	Paginator *Paginator `protobuf:"bytes,7,opt,name=paginator,proto3" json:"paginator,omitempty"`
	// Optional persistence target.
	// Selects where the entries are looked up from:
	// UNKNOWN => request will be rejected
	// PERMANENT => will be looked up inside MongoDB (default)
	// CACHED => will be looked up inside NATS
	Target        *PersistanceTarget `protobuf:"varint,8,opt,name=target,proto3,enum=octopus_sdk.v1.PersistanceTarget,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetKeyPattern() string {
	if x != nil {
		return x.KeyPattern
	}
	return ""
}

func (x *QueryRequest) GetIncludeExpired() bool {
	if x != nil && x.IncludeExpired != nil {
		return *x.IncludeExpired
	}
	return false
}

func (x *QueryRequest) GetCreatedAtRangeStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtRangeStart
	}
	return nil
}

func (x *QueryRequest) GetCreatedAtRangeEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtRangeEnd
	}
	return nil
}

func (x *QueryRequest) GetDataFilter() string {
	if x != nil && x.DataFilter != nil {
		return *x.DataFilter
	}
	return ""
}

func (x *QueryRequest) GetDataSort() string {
	if x != nil && x.DataSort != nil {
		return *x.DataSort
	}
	return ""
}

func (x *QueryRequest) GetPaginator() *Paginator {
	if x != nil {
		return x.Paginator
	}
	return nil
}

func (x *QueryRequest) GetTarget() PersistanceTarget {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return PersistanceTarget_UNKNOWN
}

// *
// For getting an exact value to a key you already have
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exact key to a object
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Optional persistance target:
	// Location of entry lookup:
	// UNKNOWN => request will be rejected
	// PERMANENT => will be saved inside the MongoDB (default)
	// CACHED => will be saved inside NATS
	Target        *PersistanceTarget `protobuf:"varint,8,opt,name=target,proto3,enum=octopus_sdk.v1.PersistanceTarget,oneof" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetTarget() PersistanceTarget {
	if x != nil && x.Target != nil {
		return *x.Target
	}
	return PersistanceTarget_UNKNOWN
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetResponse_Object
	//	*GetResponse_Empty
	Result        isGetResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetResult() isGetResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetResponse) GetObject() *Object {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *GetResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		if x, ok := x.Result.(*GetResponse_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

type isGetResponse_Result interface {
	isGetResponse_Result()
}

type GetResponse_Object struct {
	// If the key points only to one value it will be returned
	Object *Object `protobuf:"bytes,1,opt,name=object,proto3,oneof"`
}

type GetResponse_Empty struct {
	// If no object is found for the given key, this field is set
	Empty *emptypb.Empty `protobuf:"bytes,2,opt,name=empty,proto3,oneof"`
}

func (*GetResponse_Object) isGetResponse_Result() {}

func (*GetResponse_Empty) isGetResponse_Result() {}

// *
// Paginator for database entry cursor-pagination.
type Paginator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based page index (page=1 is first page)
	Page int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	// Number of items to return.
	PageSize      int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Paginator) Reset() {
	*x = Paginator{}
	mi := &file_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Paginator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Paginator) ProtoMessage() {}

func (x *Paginator) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Paginator.ProtoReflect.Descriptor instead.
func (*Paginator) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *Paginator) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Paginator) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage     int32                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`               // current page (1-based)
	CurrentPageSize int32                  `protobuf:"varint,2,opt,name=current_page_size,json=currentPageSize,proto3" json:"current_page_size,omitempty"` // current page size
	TotalPages      int32                  `protobuf:"varint,3,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`                  // last page number
	TotalItems      int64                  `protobuf:"varint,4,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`                  // total matching items
	NextPage        *int32                 `protobuf:"varint,5,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`                  // next page number. null if not present
	PrevPage        *int32                 `protobuf:"varint,6,opt,name=prev_page,json=prevPage,proto3,oneof" json:"prev_page,omitempty"`                  // previous page number. null if not present
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *PageInfo) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PageInfo) GetCurrentPageSize() int32 {
	if x != nil {
		return x.CurrentPageSize
	}
	return 0
}

func (x *PageInfo) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *PageInfo) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PageInfo) GetNextPage() int32 {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return 0
}

func (x *PageInfo) GetPrevPage() int32 {
	if x != nil && x.PrevPage != nil {
		return *x.PrevPage
	}
	return 0
}

// *
// Result of `Query` RPC.
type QueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of found entries including revision, ID and timestamps.
	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	// Page information about the cursor.
	PageInfo      *PageInfo `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *QueryResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *QueryResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

// *
// Request for creating a developer-defined MongoDB index.
type CreateIndexRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Concrete collection name. Wildcard patterns are not allowed.
	Collection string `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// Optional explicit index name. If empty, the server can generate one from
	// the requested fields.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Ordered list of fields that make up the index.
	Fields []*IndexField `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	// Whether the index should enforce unique values.
	Unique        bool `protobuf:"varint,4,opt,name=unique,proto3" json:"unique,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexRequest) Reset() {
	*x = CreateIndexRequest{}
	mi := &file_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexRequest) ProtoMessage() {}

func (x *CreateIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexRequest.ProtoReflect.Descriptor instead.
func (*CreateIndexRequest) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *CreateIndexRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *CreateIndexRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIndexRequest) GetFields() []*IndexField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *CreateIndexRequest) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

// *
// A single field inside a developer-defined index.
type IndexField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Mongo path to index, e.g. data.player_uuid, data.server, created_at.
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Index sort direction for this path.
	Direction     IndexField_IndexDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=octopus_sdk.v1.IndexField_IndexDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexField) Reset() {
	*x = IndexField{}
	mi := &file_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexField) ProtoMessage() {}

func (x *IndexField) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexField.ProtoReflect.Descriptor instead.
func (*IndexField) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *IndexField) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexField) GetDirection() IndexField_IndexDirection {
	if x != nil {
		return x.Direction
	}
	return IndexField_UNKNOWN
}

// *
// Response returned after creating or confirming an index.
type CreateIndexResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The MongoDB index name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIndexResponse) Reset() {
	*x = CreateIndexResponse{}
	mi := &file_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndexResponse) ProtoMessage() {}

func (x *CreateIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndexResponse.ProtoReflect.Descriptor instead.
func (*CreateIndexResponse) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *CreateIndexResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// *
// Message type for the listen stream.
type ListenMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pattern to match keys. Supports wildcards:
	//   - - matches exactly one token (between dots), e.g., "foo.*.bar" matches "foo.x.bar" but not "foo.x.y.bar"
	//     >  - matches one or more tokens until the end, e.g., "foo.>" matches "foo", "foo.bar", "foo.bar.baz", etc.
	//
	// Multiple wildcards can be used in a single pattern. Tokens are dot-separated.
	KeyPattern    []string `protobuf:"bytes,1,rep,name=key_pattern,json=keyPattern,proto3" json:"key_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenMessage) Reset() {
	*x = ListenMessage{}
	mi := &file_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenMessage) ProtoMessage() {}

func (x *ListenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenMessage.ProtoReflect.Descriptor instead.
func (*ListenMessage) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListenMessage) GetKeyPattern() []string {
	if x != nil {
		return x.KeyPattern
	}
	return nil
}

// *
// Represents a event in the stream.
type EventCall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The affected object.
	Object *Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// Unique ID for this event call (useful for tracking).
	CallId        string `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventCall) Reset() {
	*x = EventCall{}
	mi := &file_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCall) ProtoMessage() {}

func (x *EventCall) ProtoReflect() protoreflect.Message {
	mi := &file_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCall.ProtoReflect.Descriptor instead.
func (*EventCall) Descriptor() ([]byte, []int) {
	return file_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *EventCall) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *EventCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

var File_v1_api_proto protoreflect.FileDescriptor

const file_v1_api_proto_rawDesc = "" +
	"\n" +
	"\fv1/api.proto\x12\x0eoctopus_sdk.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x02\n" +
	"\x06Object\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x04data\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x04data\x126\n" +
	"\x17preserve_previous_entry\x18\x03 \x01(\bR\x15preservePreviousEntry\x12>\n" +
	"\n" +
	"expired_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiredAt\x88\x01\x01\x12>\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tdeletedAt\x88\x01\x01\x12>\n" +
	"\x06target\x18\x06 \x01(\x0e2!.octopus_sdk.v1.PersistanceTargetH\x02R\x06target\x88\x01\x01B\r\n" +
	"\v_expired_atB\r\n" +
	"\v_deleted_atB\t\n" +
	"\a_target\"\x9e\x01\n" +
	"\x05Entry\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.octopus_sdk.v1.ObjectR\x06object\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x03R\brevision\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\xb7\x04\n" +
	"\fQueryRequest\x12\x1f\n" +
	"\vkey_pattern\x18\x01 \x01(\tR\n" +
	"keyPattern\x12,\n" +
	"\x0finclude_expired\x18\x02 \x01(\bH\x00R\x0eincludeExpired\x88\x01\x01\x12T\n" +
	"\x16created_at_range_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x13createdAtRangeStart\x88\x01\x01\x12P\n" +
	"\x14created_at_range_end\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x11createdAtRangeEnd\x88\x01\x01\x12$\n" +
	"\vdata_filter\x18\x05 \x01(\tH\x03R\n" +
	"dataFilter\x88\x01\x01\x12 \n" +
	"\tdata_sort\x18\x06 \x01(\tH\x04R\bdataSort\x88\x01\x01\x127\n" +
	"\tpaginator\x18\a \x01(\v2\x19.octopus_sdk.v1.PaginatorR\tpaginator\x12>\n" +
	"\x06target\x18\b \x01(\x0e2!.octopus_sdk.v1.PersistanceTargetH\x05R\x06target\x88\x01\x01B\x12\n" +
	"\x10_include_expiredB\x19\n" +
	"\x17_created_at_range_startB\x17\n" +
	"\x15_created_at_range_endB\x0e\n" +
	"\f_data_filterB\f\n" +
	"\n" +
	"_data_sortB\t\n" +
	"\a_target\"i\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x06target\x18\b \x01(\x0e2!.octopus_sdk.v1.PersistanceTargetH\x00R\x06target\x88\x01\x01B\t\n" +
	"\a_target\"y\n" +
	"\vGetResponse\x120\n" +
	"\x06object\x18\x01 \x01(\v2\x16.octopus_sdk.v1.ObjectH\x00R\x06object\x12.\n" +
	"\x05empty\x18\x02 \x01(\v2\x16.google.protobuf.EmptyH\x00R\x05emptyB\b\n" +
	"\x06result\"<\n" +
	"\tPaginator\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xfb\x01\n" +
	"\bPageInfo\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x05R\vcurrentPage\x12*\n" +
	"\x11current_page_size\x18\x02 \x01(\x05R\x0fcurrentPageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x03 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_items\x18\x04 \x01(\x03R\n" +
	"totalItems\x12 \n" +
	"\tnext_page\x18\x05 \x01(\x05H\x00R\bnextPage\x88\x01\x01\x12 \n" +
	"\tprev_page\x18\x06 \x01(\x05H\x01R\bprevPage\x88\x01\x01B\f\n" +
	"\n" +
	"_next_pageB\f\n" +
	"\n" +
	"_prev_page\"w\n" +
	"\rQueryResponse\x12/\n" +
	"\aentries\x18\x01 \x03(\v2\x15.octopus_sdk.v1.EntryR\aentries\x125\n" +
	"\tpage_info\x18\x02 \x01(\v2\x18.octopus_sdk.v1.PageInfoR\bpageInfo\"\x94\x01\n" +
	"\x12CreateIndexRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x06fields\x18\x03 \x03(\v2\x1a.octopus_sdk.v1.IndexFieldR\x06fields\x12\x16\n" +
	"\x06unique\x18\x04 \x01(\bR\x06unique\"\x9b\x01\n" +
	"\n" +
	"IndexField\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12G\n" +
	"\tdirection\x18\x02 \x01(\x0e2).octopus_sdk.v1.IndexField.IndexDirectionR\tdirection\"0\n" +
	"\x0eIndexDirection\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03ASC\x10\x01\x12\b\n" +
	"\x04DESC\x10\x02\")\n" +
	"\x13CreateIndexResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\rListenMessage\x12\x1f\n" +
	"\vkey_pattern\x18\x01 \x03(\tR\n" +
	"keyPattern\"T\n" +
	"\tEventCall\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.octopus_sdk.v1.ObjectR\x06object\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId*;\n" +
	"\x11PersistanceTarget\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tPERMANENT\x10\x01\x12\n" +
	"\n" +
	"\x06CACHED\x10\x022\x9f\x03\n" +
	"\aOctopus\x12D\n" +
	"\x05Query\x12\x1c.octopus_sdk.v1.QueryRequest\x1a\x1d.octopus_sdk.v1.QueryResponse\x12>\n" +
	"\x03Get\x12\x1a.octopus_sdk.v1.GetRequest\x1a\x1b.octopus_sdk.v1.GetResponse\x127\n" +
	"\x05Write\x12\x16.octopus_sdk.v1.Object\x1a\x16.google.protobuf.Empty\x125\n" +
	"\x04Call\x12\x16.octopus_sdk.v1.Object\x1a\x15.octopus_sdk.v1.Entry\x12F\n" +
	"\x06Listen\x12\x1d.octopus_sdk.v1.ListenMessage\x1a\x19.octopus_sdk.v1.EventCall(\x010\x01\x12V\n" +
	"\vCreateIndex\x12\".octopus_sdk.v1.CreateIndexRequest\x1a#.octopus_sdk.v1.CreateIndexResponseBN\n" +
	"\x18studio.o7.octopus.sdk.v1P\x01Z0github.com/o7studios/octopus-sdk/go/v1;octopusv1b\x06proto3"

var (
	file_v1_api_proto_rawDescOnce sync.Once
	file_v1_api_proto_rawDescData []byte
)

func file_v1_api_proto_rawDescGZIP() []byte {
	file_v1_api_proto_rawDescOnce.Do(func() {
		file_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)))
	})
	return file_v1_api_proto_rawDescData
}

var file_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_v1_api_proto_goTypes = []any{
	(PersistanceTarget)(0),         // 0: octopus_sdk.v1.PersistanceTarget
	(IndexField_IndexDirection)(0), // 1: octopus_sdk.v1.IndexField.IndexDirection
	(*Object)(nil),                 // 2: octopus_sdk.v1.Object
	(*Entry)(nil),                  // 3: octopus_sdk.v1.Entry
	(*QueryRequest)(nil),           // 4: octopus_sdk.v1.QueryRequest
	(*GetRequest)(nil),             // 5: octopus_sdk.v1.GetRequest
	(*GetResponse)(nil),            // 6: octopus_sdk.v1.GetResponse
	(*Paginator)(nil),              // 7: octopus_sdk.v1.Paginator
	(*PageInfo)(nil),               // 8: octopus_sdk.v1.PageInfo
	(*QueryResponse)(nil),          // 9: octopus_sdk.v1.QueryResponse
	(*CreateIndexRequest)(nil),     // 10: octopus_sdk.v1.CreateIndexRequest
	(*IndexField)(nil),             // 11: octopus_sdk.v1.IndexField
	(*CreateIndexResponse)(nil),    // 12: octopus_sdk.v1.CreateIndexResponse
	(*ListenMessage)(nil),          // 13: octopus_sdk.v1.ListenMessage
	(*EventCall)(nil),              // 14: octopus_sdk.v1.EventCall
	(*structpb.Struct)(nil),        // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),          // 17: google.protobuf.Empty
}
var file_v1_api_proto_depIdxs = []int32{
	15, // 0: octopus_sdk.v1.Object.data:type_name -> google.protobuf.Struct
	16, // 1: octopus_sdk.v1.Object.expired_at:type_name -> google.protobuf.Timestamp
	16, // 2: octopus_sdk.v1.Object.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 3: octopus_sdk.v1.Object.target:type_name -> octopus_sdk.v1.PersistanceTarget
	2,  // 4: octopus_sdk.v1.Entry.object:type_name -> octopus_sdk.v1.Object
	16, // 5: octopus_sdk.v1.Entry.created_at:type_name -> google.protobuf.Timestamp
	16, // 6: octopus_sdk.v1.QueryRequest.created_at_range_start:type_name -> google.protobuf.Timestamp
	16, // 7: octopus_sdk.v1.QueryRequest.created_at_range_end:type_name -> google.protobuf.Timestamp
	7,  // 8: octopus_sdk.v1.QueryRequest.paginator:type_name -> octopus_sdk.v1.Paginator
	0,  // 9: octopus_sdk.v1.QueryRequest.target:type_name -> octopus_sdk.v1.PersistanceTarget
	0,  // 10: octopus_sdk.v1.GetRequest.target:type_name -> octopus_sdk.v1.PersistanceTarget
	2,  // 11: octopus_sdk.v1.GetResponse.object:type_name -> octopus_sdk.v1.Object
	17, // 12: octopus_sdk.v1.GetResponse.empty:type_name -> google.protobuf.Empty
	3,  // 13: octopus_sdk.v1.QueryResponse.entries:type_name -> octopus_sdk.v1.Entry
	8,  // 14: octopus_sdk.v1.QueryResponse.page_info:type_name -> octopus_sdk.v1.PageInfo
	11, // 15: octopus_sdk.v1.CreateIndexRequest.fields:type_name -> octopus_sdk.v1.IndexField
	1,  // 16: octopus_sdk.v1.IndexField.direction:type_name -> octopus_sdk.v1.IndexField.IndexDirection
	2,  // 17: octopus_sdk.v1.EventCall.object:type_name -> octopus_sdk.v1.Object
	4,  // 18: octopus_sdk.v1.Octopus.Query:input_type -> octopus_sdk.v1.QueryRequest
	5,  // 19: octopus_sdk.v1.Octopus.Get:input_type -> octopus_sdk.v1.GetRequest
	2,  // 20: octopus_sdk.v1.Octopus.Write:input_type -> octopus_sdk.v1.Object
	2,  // 21: octopus_sdk.v1.Octopus.Call:input_type -> octopus_sdk.v1.Object
	13, // 22: octopus_sdk.v1.Octopus.Listen:input_type -> octopus_sdk.v1.ListenMessage
	10, // 23: octopus_sdk.v1.Octopus.CreateIndex:input_type -> octopus_sdk.v1.CreateIndexRequest
	9,  // 24: octopus_sdk.v1.Octopus.Query:output_type -> octopus_sdk.v1.QueryResponse
	6,  // 25: octopus_sdk.v1.Octopus.Get:output_type -> octopus_sdk.v1.GetResponse
	17, // 26: octopus_sdk.v1.Octopus.Write:output_type -> google.protobuf.Empty
	3,  // 27: octopus_sdk.v1.Octopus.Call:output_type -> octopus_sdk.v1.Entry
	14, // 28: octopus_sdk.v1.Octopus.Listen:output_type -> octopus_sdk.v1.EventCall
	12, // 29: octopus_sdk.v1.Octopus.CreateIndex:output_type -> octopus_sdk.v1.CreateIndexResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_v1_api_proto_init() }
func file_v1_api_proto_init() {
	if File_v1_api_proto != nil {
		return
	}
	file_v1_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_v1_api_proto_msgTypes[4].OneofWrappers = []any{
		(*GetResponse_Object)(nil),
		(*GetResponse_Empty)(nil),
	}
	file_v1_api_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_api_proto_rawDesc), len(file_v1_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_api_proto_goTypes,
		DependencyIndexes: file_v1_api_proto_depIdxs,
		EnumInfos:         file_v1_api_proto_enumTypes,
		MessageInfos:      file_v1_api_proto_msgTypes,
	}.Build()
	File_v1_api_proto = out.File
	file_v1_api_proto_goTypes = nil
	file_v1_api_proto_depIdxs = nil
}
